; servo_ls TRIAL - Limit Switch Atas + LED + Servo
; Board: Black Pill WeAct V2 — STM32F411CEU6
; LS_UP: PB6 (INPUT_PULLUP), Servo: PB9 (TIM11_CH1), LED: PC13 onboard

[env:blackpill_f411ce]
platform = ststm32
board = blackpill_f411ce
framework = arduino
upload_protocol = stlink
monitor_speed = 115200

build_flags =
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -DUSBCON
