; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:blackpill_f411ce]
platform = ststm32
board = blackpill_f411ce
framework = arduino

; TFT Library - ILI9341 driver
; Touch Library - XPT2046 resistive touchscreen
lib_deps =
    adafruit/Adafruit GFX Library@^1.11.7
    adafruit/Adafruit ILI9341@^1.5.9
    tedtoal/XPT2046_Touchscreen_TT@^1.8.1

; Build flags
build_flags =
    -D STM32F411CEU6
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320

; Serial monitor
monitor_speed = 115200
monitor_filters = time

; Upload protocol (ST-Link)
upload_protocol = stlink