'use strict';
const $=id=>document.getElementById(id); const q=(s,r=document)=>r.querySelector(s); const qa=(s,r=document)=>[...r.querySelectorAll(s)];
const state={}; let updated={}; let serverDelta=0; let sse=null; let experiments={}; let configs={}; let currentExp='navigation'; let mapImage=null; let mapTransform={scale:1,ox:0,oy:0,fit:true}; const history=[];
const deg=r=>Number.isFinite(+r)?+r*180/Math.PI:null; const fmt=(v,n=2,s='--')=>Number.isFinite(+v)?(+v).toFixed(n):s; const bool=v=>v===true; const raw=k=>state[k]; const obj=k=>(state[k]&&typeof state[k]==='object')?state[k]:{};
const textish=o=>{if(o==null)return '--';if(typeof o==='string')return o;if(typeof o==='boolean')return o?'TRUE':'FALSE';if(typeof o==='number')return fmt(o,3);if(o.raw)return String(o.raw);return JSON.stringify(o)};
function pretty(o){if(o==null)return 'No data.'; return typeof o==='string'?o:JSON.stringify(o,null,2)}
function setText(id,v){const e=$(id);if(e)e.textContent=v}
function setChip(id,ok,labelOk='READY',labelWait='WAIT'){const e=$(id);if(!e)return;e.classList.remove('waiting','bad'); if(ok===true){e.textContent=labelOk}else if(ok===false){e.textContent=labelWait;e.classList.add('bad')}else{e.textContent=labelWait;e.classList.add('waiting')}}
function age(k){const t=updated[k];return t?Math.max(0,(Date.now()-t)/1000):Infinity}
function channelFresh(k,sec=3){return age(k)<sec}
function healthCard(name,status,detail){const el=q(`[data-health="${name}"]`);if(!el)return;el.classList.remove('ok','warn','bad');el.classList.add(status);const b=q('b',el),small=q('small',el);if(b)b.textContent=status==='ok'?'ONLINE':status==='warn'?'WAIT':'OFFLINE';if(small&&detail)small.textContent=detail}
function getPath(o,...keys){for(const k of keys){if(o&&o[k]!=null)return o[k]}return null}
function statusRaw(k){const o=obj(k);return o.raw||textish(o)}
function pageName(p){return {overview:['SYSTEM MONITOR','Overview'],navigation:['NAV2 WORKSPACE','Navigation'],perception:['VISION SYSTEM','Perception'],sensors:['SENSOR INPUT','LiDAR & IMU'],esc:['ACTUATION','ESC & Steering'],calibration:['COMMISSIONING','Calibration Center'],tuning:['CONTROL ENGINEERING','Tuning & Control'],experiments:['THESIS DATA','Data BAB IV'],reports:['EVIDENCE','Reports & Export'],diagnostics:['ENGINEERING','Diagnostics'],configuration:['SYSTEM SOURCE','Configuration']}[p]||['SYSTEM','Dashboard']}
qa('.nav-item').forEach(b=>b.addEventListener('click',()=>{qa('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');qa('.page').forEach(x=>x.classList.remove('active'));$(`page-${b.dataset.page}`).classList.add('active');const [e,t]=pageName(b.dataset.page);setText('pageEyebrow',e);setText('pageTitle',t);$('sidebar').classList.remove('open'); if(b.dataset.page==='navigation')drawMap();}));
$('menuButton').onclick=()=>$('sidebar').classList.toggle('open'); $('sidebarBackdrop').onclick=()=>$('sidebar').classList.remove('open'); document.addEventListener('keydown',e=>{if(e.key==='Escape')$('sidebar').classList.remove('open')}); $('themeButton').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('adv-theme',document.body.classList.contains('light')?'light':'dark');drawMap()}; if(localStorage.getItem('adv-theme')==='light')document.body.classList.add('light');
function toast(msg,bad=false){const e=document.createElement('div');e.className='toast'+(bad?' bad':'');e.textContent=msg;$('toastStack').append(e);setTimeout(()=>e.remove(),4200)}
let confirmAction=null;function confirmModal(title,text,fn){setText('confirmTitle',title);setText('confirmText',text);confirmAction=fn;$('confirmModal').classList.add('show')}$('confirmNo').onclick=()=>{$('confirmModal').classList.remove('show');confirmAction=null};$('confirmYes').onclick=()=>{const fn=confirmAction;$('confirmModal').classList.remove('show');confirmAction=null;if(fn)fn()};
async function post(url,body={}){try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();toast(j.message||(`${r.status} ${r.statusText}`),!r.ok);return j}catch(e){toast('Request gagal: '+e.message,true);return null}}
function merge(delta){if(!delta||typeof delta!=='object')return;const ups=delta.__updated||{};Object.entries(delta).forEach(([k,v])=>{if(!k.startsWith('__'))state[k]=v});Object.assign(updated,ups);if(delta.__server_time_ms)serverDelta=Date.now()-delta.__server_time_ms;render();captureLabTelemetry()}
async function fullState(){try{const r=await fetch('/api/state',{cache:'no-store'});merge(await r.json())}catch(e){}}
function connectSse(){if(sse)sse.close();sse=new EventSource('/api/events');sse.onopen=()=>{setText('sseLabel','Live stream');$('sseDot').style.background='var(--green)';setText('diagSse','CONNECTED');setText('footerStatus','ROS2 realtime telemetry connected')};sse.addEventListener('snapshot',e=>{try{merge(JSON.parse(e.data))}catch(_){}});sse.onmessage=e=>{try{merge(JSON.parse(e.data))}catch(_){}};sse.onerror=()=>{setText('sseLabel','Reconnecting');$('sseDot').style.background='var(--amber)';setText('diagSse','RETRYING');setText('footerStatus','Reconnecting realtime telemetry…')}}
function healthFromConnected(key){if(bool(raw(key))&&channelFresh(key,5))return'ok';return channelFresh(key,8)?'warn':'bad'}
function renderOverview(){const li=healthFromConnected('connected.lidar'),im=healthFromConnected('connected.imu'),ca=healthFromConnected('connected.camera'),es=bool(raw('connected.esc_feedback'))?'ok':(bool(raw('connected.esc_ready'))?'warn':'bad');const motion=bool(raw('system.motion_ready'))||bool(raw('system.autonomy_motion_allowed'));const loc=channelFresh('amcl',4)?'ok':(channelFresh('ekf_local',4)?'warn':'bad');const nv=bool(raw('system.nav2_ready'))?'ok':(channelFresh('nav2_runtime',5)?'warn':'bad');const ld=obj('lidar');healthCard('lidar',li,Number.isFinite(+ld.scan_rate_hz)?fmt(ld.scan_rate_hz,1)+' Hz / '+fmt(ld.valid_ratio_pct,1)+'% valid':'waiting /scan_nav');healthCard('imu',im,channelFresh('imu',3)?'data /imu/data fresh':'waiting /imu/data');healthCard('camera',ca,obj('camera_frame').source||'Astra Pro');healthCard('esc',es,bool(raw('connected.esc_feedback'))?'ACK fresh':'waiting ESC ACK');healthCard('localization',loc,channelFresh('amcl',4)?'AMCL pose fresh':'waiting /amcl_pose');healthCard('nav2',nv,bool(raw('system.nav2_ready'))?'planner/controller/BT present':'waiting Nav2 runtime');const states=[li,im,ca,es,loc,nv],score=Math.round(states.reduce((a,x)=>a+(x==='ok'?1:x==='warn'?.5:0),0)/states.length*100);$('readinessRing').style.setProperty('--pct',score);setText('readinessPct',score+'%');setText('readinessTitle',motion?'Vehicle motion-ready':score>=70?'Core runtime online, safety gates pending':'System commissioning / offline');setText('readinessDetail',motion?'Localization, Nav2 and actuator safety gates report ready.':'Periksa LiDAR, IMU, AMCL, Nav2, perception, dan ESC. Motion tetap fail-closed sampai gate aktual siap.');setText('overallChip',motion?'MOTION READY':'FAIL-CLOSED');$('overallChip').className='status-chip '+(motion?'':'waiting');const pose=channelFresh('amcl',5)?obj('amcl'):obj('ekf_local'),imu=obj('imu');setText('overviewSpeed',fmt(getPath(obj('esc_odom'),'v')??getPath(obj('ekf_local'),'v')));setText('overviewSteer',fmt(deg(raw('esc_steer_actual')),1));setText('overviewYaw',fmt(deg(getPath(pose,'yaw')??getPath(imu,'yaw_rad')),1));setText('goalStateBig',getPath(obj('goal_state'),'state')||'IDLE');setText('activeSourceBig','ACTUATOR: '+(getPath(obj('esc_mux'),'raw')||'--'));setText('lastUpdate',new Date().toLocaleTimeString('id-ID'));const cn=obj('cmd_nav'),cs=obj('cmd_autonomy_integrated'),cf=obj('cmd_final'),caa=obj('cmd_actuator');setText('pipeNav',fmt(cn.linear_x));setText('pipeSafety',fmt(cs.linear_x));setText('pipeFinal',fmt(cf.linear_x));setText('pipeActuator',fmt(caa.linear_x));history.push({t:Date.now(),nav:+cn.linear_x||0,final:+cf.linear_x||0,actual:+raw('esc_drive_actual')||0});while(history.length>180)history.shift();drawSpark();renderAlerts();}
function renderAlerts(){const a=[];if(bool(raw('system.estop')))a.push(['danger','Emergency stop ACTIVE']);if(bool(raw('perception_emergency')))a.push(['danger','Perception emergency stop ACTIVE']);if(!bool(raw('connected.esc_feedback')))a.push(['danger','ESC ACK belum fresh - motor command tidak dianggap ready']);if(!bool(raw('connected.lidar')))a.push(['warn','LiDAR /scan_nav belum fresh']);if(!bool(raw('connected.imu')))a.push(['warn','IMU /imu/data belum fresh']);if(!channelFresh('amcl',4))a.push(['warn','AMCL pose belum fresh']);if(!(bool(raw('system.motion_ready'))||bool(raw('system.autonomy_motion_allowed'))))a.push(['warn','Motion gate masih tertutup']);if((bool(raw('system.motion_ready'))||bool(raw('system.autonomy_motion_allowed')))&&bool(raw('connected.esc_feedback')))a.push(['ok','Core motion chain ready']);setText('alertCount',a.filter(x=>x[0]!=='ok').length);$('alerts').innerHTML=a.length?a.map(x=>'<div class="alert-item '+x[0]+'">'+escapeHtml(x[1])+'</div>').join(''):'<div class="empty-state">Tidak ada kondisi aktif.</div>';}
function drawSpark(){const c=$('speedSpark'),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);const css=getComputedStyle(document.body);ctx.strokeStyle=css.getPropertyValue('--border2');ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(0,h/2);ctx.lineTo(w,h/2);ctx.stroke();if(history.length<2)return;const max=Math.max(1,...history.flatMap(x=>[Math.abs(x.nav),Math.abs(x.final),Math.abs(x.actual)]));[['nav','--blue'],['final','--green'],['actual','--cyan']].forEach(([key,col])=>{ctx.strokeStyle=css.getPropertyValue(col);ctx.lineWidth=2;ctx.beginPath();history.forEach((p,i)=>{const x=i/(history.length-1)*w,y=h/2-(p[key]/max)*(h*.38);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()})}
function renderNavigation(){const p=channelFresh('amcl',5)?obj('amcl'):obj('ekf_local'),path=obj('nav_path');setText('poseX',fmt(p.x,3));setText('poseY',fmt(p.y,3));setText('poseYaw',fmt(deg(p.yaw),1)+'°');setText('poseV',fmt(getPath(obj('ekf_local'),'v')??getPath(obj('esc_odom'),'v'),3)+' m/s');setText('pathLength',fmt(path.length_m,2)+' m');setText('navGoalState',getPath(obj('goal_state'),'state')||'--');setText('navReady',bool(raw('system.nav2_ready'))?'READY':'WAIT');setText('mppiReady',bool(raw('mppi_closed_loop_ready'))?'READY':'WAIT');setText('collisionState',getPath(obj('collision_monitor_state'),'state','raw')||'--');drawMap();}
function loadMapImage(){const im=new Image();im.onload=()=>{mapImage=im;$('mapPlaceholder').style.display='none';drawMap()};im.onerror=()=>{};im.src='/api/map.png?'+Date.now()}
function worldToPx(x,y,c,meta){const mx=(x-meta.origin_x)/meta.resolution,my=(y-meta.origin_y)/meta.resolution;const sx=c.width/meta.width,sy=c.height/meta.height;return [mx*sx,my*sy]}
function drawMap(){const c=$('mapCanvas');if(!c)return;const rect=c.getBoundingClientRect();if(rect.width>0){const dpr=Math.min(devicePixelRatio||1,2);const nw=Math.round(rect.width*dpr),nh=Math.round(rect.height*dpr);if(c.width!==nw||c.height!==nh){c.width=nw;c.height=nh}}const ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.fillStyle=document.body.classList.contains('light')?'#e7eeee':'#050b0d';ctx.fillRect(0,0,w,h);const m=obj('map_meta');if(!mapImage||!m.width||!m.height)return;const scale=Math.min(w/mapImage.width,h/mapImage.height),dw=mapImage.width*scale,dh=mapImage.height*scale,ox=(w-dw)/2,oy=(h-dh)/2;ctx.save();ctx.translate(ox,oy);ctx.scale(scale,scale);ctx.drawImage(mapImage,0,0);ctx.restore();const trans=(x,y)=>{const px=(x-m.origin_x)/m.resolution, py=(y-m.origin_y)/m.resolution;return [ox+px*scale,oy+(m.height-py)*scale]};const css=getComputedStyle(document.body);function pathDraw(key,color,width){const pts=obj(key).points||[];if(pts.length<2)return;ctx.strokeStyle=css.getPropertyValue(color);ctx.lineWidth=width*(devicePixelRatio||1);ctx.beginPath();pts.forEach((p,i)=>{const [x,y]=trans(p[0],p[1]);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}pathDraw('nav_path','--blue',2);pathDraw('local_path','--cyan',2);const goal=obj('goal_pose');if(Number.isFinite(+goal.x)){const [x,y]=trans(goal.x,goal.y);ctx.fillStyle=css.getPropertyValue('--red');ctx.beginPath();ctx.arc(x,y,7*(devicePixelRatio||1),0,Math.PI*2);ctx.fill()}const pose=channelFresh('amcl',5)?obj('amcl'):obj('ekf_local');if(Number.isFinite(+pose.x)){const [x,y]=trans(pose.x,pose.y),r=8*(devicePixelRatio||1);ctx.save();ctx.translate(x,y);ctx.rotate(-(pose.yaw||0));ctx.fillStyle=css.getPropertyValue('--green');ctx.beginPath();ctx.moveTo(r*1.5,0);ctx.lineTo(-r,r);ctx.lineTo(-r,-r);ctx.closePath();ctx.fill();ctx.restore()}mapTransform.trans=trans}
$('mapCanvas').addEventListener('click',e=>{const m=obj('map_meta');if(!mapImage||!m.width)return;const c=$('mapCanvas'),rect=c.getBoundingClientRect(),dpr=c.width/rect.width,px=(e.clientX-rect.left)*dpr,py=(e.clientY-rect.top)*dpr,scale=Math.min(c.width/mapImage.width,c.height/mapImage.height),ox=(c.width-mapImage.width*scale)/2,oy=(c.height-mapImage.height*scale)/2;const mx=(px-ox)/scale,my=m.height-(py-oy)/scale;if(mx<0||my<0||mx>m.width||my>m.height)return;$('goalX').value=(m.origin_x+mx*m.resolution).toFixed(2);$('goalY').value=(m.origin_y+my*m.resolution).toFixed(2)});
$('sendGoalBtn').onclick=()=>confirmModal('Send navigation goal',`Kirim goal map X=${$('goalX').value}, Y=${$('goalY').value}, yaw=${$('goalYaw').value}°?`,()=>post('/api/navigation/goal',{x:+$('goalX').value,y:+$('goalY').value,yaw_deg:+$('goalYaw').value}));$('cancelGoalBtn').onclick=()=>confirmModal('Cancel navigation','Batalkan goal Nav2 yang sedang aktif?',()=>post('/api/navigation/cancel'));$('usePoseForInitial').onclick=()=>{const p=channelFresh('amcl',5)?obj('amcl'):obj('ekf_local');if(!Number.isFinite(+p.x))return toast('Pose map belum tersedia',true);confirmModal('Publish initial pose','Gunakan estimator saat ini sebagai /initialpose?',()=>post('/api/localization/initial-pose',{x:+p.x,y:+p.y,yaw_rad:+p.yaw}))};$('resetLocalizationBtn').onclick=()=>confirmModal('Reset localization samples','Reset sampel kalibrasi localization?',()=>post('/api/localization/reset-calibration'));$('mapCenterBtn').onclick=drawMap;$('mapFitBtn').onclick=()=>{loadMapImage()};
function renderPerception(){const conn=bool(raw('connected.camera')),healthy=bool(raw('camera_healthy'));setChip('cameraChip',conn&&healthy,'HEALTHY',conn?'DEGRADED':'OFFLINE');const f=obj('camera_frame');setText('cameraSource',f.source||'--');setText('cameraResolution',f.width?`${f.width}×${f.height}`:'--');setText('laneState',getPath(obj('lane_state'),'state','raw')||'--');setText('laneControl',getPath(obj('lane_control'),'state','raw')||'--');setText('drivableState',getPath(obj('drivable_space'),'state','raw')||'--');setText('nearFieldState',getPath(obj('near_field_state'),'state','raw')||'--');setText('cloudObjects',obj('object_points').count??'--');setText('cloudPath',obj('path_relevant_points').count??'--');setText('cloudPlanning',obj('planning_relevant_points').count??'--');setText('cloudBoundary',obj('drivable_boundary_points').count??'--');setText('perceptionPerformance',pretty(obj('perception_performance')));setText('detectionsView',pretty({obstacle:obj('obstacle_metrics'),detections:obj('raw_detections')}))}
function updateCamera(){const img=$('cameraImage');if(!bool(raw('connected.camera')))return;const src='/api/camera.jpg?t='+Date.now();const pre=new Image();pre.onload=()=>{img.src=src;img.style.display='block';$('cameraPlaceholder').style.display='none'};pre.src=src}
function renderSensors(){const ld=obj('lidar'),ls=obj('lidar_safety'),im=obj('imu');setChip('lidarChip',bool(raw('connected.lidar'))&&channelFresh('lidar',3),'STREAMING','OFFLINE');setText('lidarCenter',Number.isFinite(+ld.range_center_m)?fmt(ld.range_center_m,3)+' m':'--');setText('lidarValid',Number.isFinite(+ld.valid_ratio_pct)?fmt(ld.valid_ratio_pct,1)+' %':'--');setText('lidarRate',Number.isFinite(+ld.scan_rate_hz)?fmt(ld.scan_rate_hz,1)+' Hz':'--');setText('lidarSamples',Number.isFinite(+ld.samples)?fmt(ld.samples,0):'--');setText('lidarDropout',Number.isFinite(+ld.dropout_pct)?fmt(ld.dropout_pct,1)+' %':'--');setText('lidarMin',Number.isFinite(+ld.range_min_observed_m)?fmt(ld.range_min_observed_m,3)+' m':'--');setText('lidarMax',Number.isFinite(+ld.range_max_observed_m)?fmt(ld.range_max_observed_m,3)+' m':'--');setText('lidarSafety',channelFresh('lidar_safety',3)?'FRESH':'WAIT');setChip('imuChip',bool(raw('connected.imu'))&&channelFresh('imu',3),'STREAMING','OFFLINE');setText('imuRoll',fmt(deg(im.roll_rad),1)+'°');setText('imuPitch',fmt(deg(im.pitch_rad),1)+'°');setText('imuYaw',fmt(deg(im.yaw_rad),1)+'°');['Gx','Gy','Gz','Ax','Ay','Az'].forEach(x=>setText('imu'+x,fmt(im[x.toLowerCase()],3)));if(Number.isFinite(+im.yaw_rad))$('imuNeedle').style.transform='rotate('+deg(im.yaw_rad)+'deg)';setText('lidarDetail',pretty({scan:ld,safety:ls,driver:obj('lidar_driver_status'),safety_status:obj('lidar_safety_health')}));setText('localizationDetail',pretty({amcl:obj('amcl'),ekf:obj('ekf_local'),runtime:obj('nav2_runtime'),planner:obj('planner_status')}));}
function renderEsc(){const ack=bool(raw('connected.esc_feedback')),ready=bool(raw('connected.esc_ready')),armed=bool(raw('connected.esc_armed'));setChip('escChip',ready,armed?'ARMED':'READY',ack?'ACK / NOT READY':'OFFLINE');$('escOrb').classList.toggle('ok',ack);setText('escConnectionTitle',ack?(ready?'ACK + READY':'ACK received, firmware not ready'):'No ESC ACK');setText('escConnectionDetail',ack?'Serial protocol is receiving fresh firmware acknowledgement.':'Expected CH340 on physical path usb-0:1.1:1.0. If ttyUSB2 exists but this remains offline, check by-path, permission, baud and firmware ACK.');setText('escDriveTarget',fmt(raw('esc_drive_target'),3)+' m/s');setText('escDriveActual',fmt(raw('esc_drive_actual'),3)+' m/s');setText('escSteerTarget',fmt(deg(raw('esc_steer_target')),2)+'°');setText('escSteerActual',fmt(deg(raw('esc_steer_actual')),2)+'°');setText('escYawRate',fmt(raw('esc_yaw_rate'),3)+' rad/s');setText('escMuxSource',getPath(obj('esc_mux'),'raw')||'--');setText('calControllerReady',bool(raw('esc_calibration_controller_ready'))?'READY':'WAIT');setText('escRawCommand',fmt(deg(raw('esc_steer_protocol_cmd')),2)+'°');setText('escRawFeedback',fmt(deg(raw('esc_steer_feedback_raw')),2)+'°');setText('escPhysicalFeedback',fmt(deg(raw('esc_steer_actual')),2)+'°');setText('escStatusRaw',pretty(obj('esc_status')));setText('focTelemetry',Object.keys(obj('foc_telemetry')).length?pretty(obj('foc_telemetry')):'Topic /esc/foc/telemetry belum tersedia.');setChip('calibrationChip',bool(raw('esc_calibration_controller_ready')),'CONTROLLER READY','SAFE');renderEscChecklist()}
function renderEscChecklist(){const sr=obj('esc_status'),mux=getPath(obj('esc_mux'),'raw')||'',items=[['Serial path',channelFresh('esc_status',3),statusRaw('esc_status').includes('serial=connected')?'connected':'expected usb-0:1.1:1.0'],['Drive channel',bool(raw('connected.esc_drive')),bool(raw('connected.esc_drive'))?'connected':'not connected'],['Steer channel',bool(raw('connected.esc_steer')),bool(raw('connected.esc_steer'))?'connected':'not connected'],['Firmware ACK',bool(raw('connected.esc_feedback')),bool(raw('connected.esc_feedback'))?'fresh ACK':'ACK stale / none'],['Firmware ready',bool(raw('connected.esc_ready')),bool(raw('connected.esc_ready'))?'both channels ready':'check status flags'],['Command source',mux&&!['IDLE','STOP'].includes(mux),mux||'IDLE'],['Drive command',Math.abs(+raw('esc_drive_target')||0)>.001,fmt(raw('esc_drive_target'),3)+' m/s'],['E-STOP clear',!bool(raw('system.estop')),bool(raw('system.estop'))?'ACTIVE':'clear'],['Calibration drive lock',true,'drive=0 while steering calibration ON'],['Motor feedback',Math.abs(+raw('esc_drive_actual')||0)>.001,fmt(raw('esc_drive_actual'),3)+' m/s']];$('escChecklist').innerHTML=items.map(([t,ok,d])=>`<div class="check-item ${ok?'ok':'bad'}"><i>${ok?'✓':'!'}</i><div><b>${escapeHtml(t)}</b><span>${escapeHtml(String(d))}</span></div></div>`).join('')}
$('calModeOn').onclick=()=>confirmModal('Enable steering calibration','Drive command will be forced to zero. Ensure steering mechanism is safe to move.',()=>post('/api/steering/calibration-mode',{enabled:true}));$('calModeOff').onclick=()=>post('/api/steering/calibration-mode',{enabled:false});$('calModeOn2').onclick=()=>confirmModal('Enable safe steering calibration','Drive output is forced to zero while calibration mode is active.',()=>post('/api/steering/calibration-mode',{enabled:true}));$('calModeOff2').onclick=()=>post('/api/steering/calibration-mode',{enabled:false});$('calResetLocalization').onclick=()=>confirmModal('Reset localization samples','Reset runtime localization samples?',()=>post('/api/localization/reset-calibration'));
function configData(name){const c=configs[name]||{};return (c.data&&typeof c.data==='object')?c.data:{}}
function findDeep(o,key){if(!o||typeof o!=='object')return undefined;if(Object.prototype.hasOwnProperty.call(o,key))return o[key];for(const v of Object.values(o)){if(v&&typeof v==='object'){const r=findDeep(v,key);if(r!==undefined)return r}}return undefined}
function passText(v){return v===true?'PASS':v===false?'WAIT':'--'}
function renderCalibration(){const steering=findDeep(configData('vehicle'),'steering_calibration_valid'),circle=findDeep(configData('vehicle'),'steering_circle_calibration_valid'),drive=findDeep(configData('vehicle'),'drive_odometry_calibration_valid'),imuValid=findDeep(configData('imu'),'stationary_calibration_valid'),cameraMetric=findDeep(configData('perception'),'camera_metric_calibration_validated');setText('calSteeringFlag',passText(steering));setText('calCircleFlag',passText(circle));setText('calDriveFlag',passText(drive));setText('calImuFlag',passText(imuValid));const amclFresh=channelFresh('amcl',4),navReady=bool(raw('system.nav2_ready')),motion=bool(raw('system.motion_ready'))||bool(raw('system.autonomy_motion_allowed'));setChip('calLocChip',amclFresh,'AMCL FRESH','WAIT');setText('calLocMode',amclFresh?'AMCL + saved map':'WAIT');setText('calAmclFresh',amclFresh?'FRESH':'STALE / WAIT');setText('calPlanningReady',navReady?'READY':'WAIT');setText('calMotionReady',motion?'ALLOWED':'LOCKED');const steerReady=bool(raw('esc_calibration_controller_ready'));setChip('calSteerChip',steering===true&&steerReady,'CALIBRATED','WAIT');setText('calSteerController',steerReady?'READY':'WAIT');setText('calSteerTarget',fmt(deg(raw('esc_steer_target')),2)+'°');setText('calSteerActual',fmt(deg(raw('esc_steer_actual')),2)+'°');setText('calSteerProtocol',fmt(deg(raw('esc_steer_feedback_raw')),2)+'°');const cam=bool(raw('connected.camera')),healthy=bool(raw('camera_healthy')),fresh=channelFresh('camera_frame',3);setChip('calCameraChip',cameraMetric===true&&healthy,'VALIDATED','WAIT');setText('calCameraUsb',cam?'CONNECTED':'OFFLINE');setText('calCameraHealth',healthy?'HEALTHY':'WAIT');setText('calCameraMetric',passText(cameraMetric));setText('calPerceptionFresh',fresh?'FRESH':'STALE / WAIT');const im=obj('imu');setChip('calImuChip',imuValid===true&&bool(raw('connected.imu')),'VALIDATED','WAIT');setText('calImuUsb',bool(raw('connected.imu'))?'CONNECTED':'OFFLINE');setText('calImuStationary',passText(imuValid));setText('calImuYaw',fmt(deg(im.yaw_rad),2)+'°');setText('calImuGz',fmt(im.gz,4)+' rad/s');}
function drawTuneSpark(){const c=$('tuneSpark');if(!c)return;const ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);const css=getComputedStyle(document.body);ctx.strokeStyle=css.getPropertyValue('--border2');ctx.beginPath();ctx.moveTo(0,h/2);ctx.lineTo(w,h/2);ctx.stroke();if(history.length<2)return;const max=Math.max(.2,...history.flatMap(x=>[Math.abs(x.final),Math.abs(x.actual)]));[['final','--green'],['actual','--cyan']].forEach(([key,col])=>{ctx.strokeStyle=css.getPropertyValue(col);ctx.lineWidth=2;ctx.beginPath();history.forEach((p,i)=>{const x=i/(history.length-1)*w,y=h/2-(p[key]/max)*(h*.40);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()})}
function renderTuning(){setText('tuneMppiReady',bool(raw('mppi_closed_loop_ready'))?'READY':'WAIT');setText('tuneSmoother',bool(raw('smoother_closed_loop_eligible'))?'ELIGIBLE':'WAIT');setText('tuneVelErr',fmt(raw('mppi_velocity_error'),3)+' m/s');setText('tuneSteerErr',fmt(deg(raw('mppi_steering_error')),2)+'°');setText('tuneNavCmd',fmt(obj('cmd_nav').linear_x,3)+' m/s');setText('tuneFinalCmd',fmt(obj('cmd_final').linear_x,3)+' m/s');setText('tuneDriveTarget',fmt(raw('esc_drive_target'),3)+' m/s');setText('tuneDriveActual',fmt(raw('esc_drive_actual'),3)+' m/s');setText('tuneSteerTarget',fmt(deg(raw('esc_steer_target')),2)+'°');setText('tuneSteerActual',fmt(deg(raw('esc_steer_actual')),2)+'°');setText('tuneQualification',pretty({mppi:obj('mppi_status'),smoother:obj('smoother_qualification'),velocity_error_mps:raw('mppi_velocity_error'),steering_error_rad:raw('mppi_steering_error'),yaw_rate_error_rps:raw('mppi_yaw_error')}));setText('tuneNavConfig',pretty(configData('nav2')));setText('tuneVehicleConfig',pretty({vehicle:configData('vehicle'),esc:configData('esc'),teleop:configData('teleop')}));drawTuneSpark()}
function currentWarnings(){let n=0;if(bool(raw('system.estop')))n++;if(!bool(raw('connected.esc_feedback')))n++;if(!bool(raw('connected.lidar')))n++;if(!bool(raw('connected.imu')))n++;if(!bool(raw('system.motion_ready')))n++;return n}
function renderReports(){const keys=Object.keys(state),fresh=keys.filter(k=>age(k)<3).length;setText('reportChannels',keys.length);setText('reportFresh',fresh);setText('reportWarnings',currentWarnings());setText('reportTimestamp','Snapshot '+new Date().toLocaleString('id-ID'));setText('reportSnapshot',pretty({goal:obj('goal_state'),pose:obj('amcl'),lidar:obj('lidar'),imu:obj('imu'),esc:{status:obj('esc_status'),target:raw('esc_drive_target'),actual:raw('esc_drive_actual')},perception:obj('perception_performance'),safety:{motion_ready:raw('system.motion_ready'),estop:raw('system.estop')}}))}
function downloadBlob(name,type,text){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function stamp(){return new Date().toISOString().replace(/[:.]/g,'-')}
function csvCell(v){const s=typeof v==='string'?v:JSON.stringify(v);return '"'+String(s??'').replace(/"/g,'""')+'"'}
function exportSummaryCsv(){const rows=[['channel','value','age_s'],...Object.keys(state).sort().map(k=>[k,textish(state[k]),Number.isFinite(age(k))?age(k).toFixed(3):''])];downloadBlob('adv_runtime_'+stamp()+'.csv','text/csv;charset=utf-8',rows.map(r=>r.map(csvCell).join(',')).join('\n'))}
function renderDiagnostics(){setText('diagChannels',Object.keys(state).length);setText('diagLatency',Math.abs(serverDelta)+' ms');setText('diagReadOnly',obj('server').read_only?'READ ONLY':'CONTROL');setText('webAction',pretty(obj('web_action')));setText('rawState',JSON.stringify(state,null,2));const keys=['system.autonomy_ready','system.motion_ready','system.nav2_ready','connected.lidar','connected.imu','connected.camera','connected.esc_ready','connected.esc_feedback','amcl','lidar_driver_status','imu_driver_status','ekf_local_status','ekf_global_status','trajectory_safety_state','collision_monitor_state','esc_status'];$('diagnosticTable').innerHTML=keys.map(k=>`<div class="diag-row"><span>${escapeHtml(k)}</span><b>${age(k)<3?'LIVE':age(k)<10?'STALE':'WAIT'}</b><code>${escapeHtml(textish(raw(k)))}</code></div>`).join('')}
function renderTop(){const ros=obj('server').ros===true;setText('rosStatus',ros?'ONLINE':'WAIT');$('rosDot').style.background=ros?'var(--green)':'var(--amber)';const mot=bool(raw('system.motion_ready'));setText('motionStatus',mot?'READY':'LOCKED');$('motionDot').style.background=mot?'var(--green)':'var(--amber)';const e=bool(raw('system.estop'));setText('estopStatus',e?'ACTIVE':'CLEAR');$('estopPill').classList.toggle('active',e);setText('serverClock',new Date().toLocaleTimeString('id-ID'))}
function render(){renderTop();renderOverview();renderNavigation();renderPerception();renderSensors();renderEsc();renderCalibration();renderTuning();renderReports();renderDiagnostics()}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
// ================= BAB IV / TUNING WORKBENCH V2 =================
let selectedExperiment=null, selectedTableIndex=0, selectedGraphIndex=0;
const metricHistory=new Map(), scatterHistory=new Map(), localRunValues={};
let recordStartedMs=0, recordUiTimer=null;
const LAB_COLORS=['#48e0a4','#55b8ff','#ffc86b','#bd8cff','#ff7b8a','#54d6e8','#9ce36b'];
const F=(label,file,path,kind='float',readOnly=false,help='')=>({label,yamlFileKey:file,yamlPath:path,kind:readOnly?'yaml_readonly':kind,help});
const WEB_TUNING={
  perception:{
    '4.1.1':[F('Inference CPU target FPS','perception','perception.ros__parameters.cpu_inference_fps'),F('CPU threads','perception','perception.ros__parameters.cpu_threads','int'),F('Camera FPS','perception','perception.ros__parameters.fps','int',true)],
    '4.1.2':[F('RGB width','perception','perception.ros__parameters.rgb_width','int'),F('RGB height','perception','perception.ros__parameters.rgb_height','int'),F('Camera FPS','perception','perception.ros__parameters.fps','int'),F('Strict camera mode','perception','perception.ros__parameters.strict_camera_mode','bool'),F('V4L2 buffer count','perception','perception.ros__parameters.v4l2_buffer_count','int')],
    '4.1.3':[F('Pixel format','perception','perception.ros__parameters.v4l2_pixel_format','string'),F('Allow MJPEG CPU fallback','perception','perception.ros__parameters.allow_mjpeg_cpu_fallback','bool'),F('Flip horizontal','perception','perception.ros__parameters.flip_horizontal','bool')],
    '4.1.4':[F('RViz max publish rate','perception','perception.ros__parameters.rviz_max_publish_rate_hz'),F('Publish annotated','perception','perception.ros__parameters.publish_annotated','bool'),F('Publish raw RGB','perception','perception.ros__parameters.publish_raw_rgb','bool'),F('Async RViz publish','perception','perception.ros__parameters.async_rviz_publish','bool')],
    '4.2.1':[F('Minimum obstacle confidence','perception','perception.ros__parameters.minimum_obstacle_confidence'),F('Raw confidence threshold','perception','perception.ros__parameters.confidence_threshold'),F('NMS IoU threshold','perception','perception.ros__parameters.iou_threshold')],
    '4.2.2':[F('Require drivable contact','perception','perception.ros__parameters.require_drivable_contact','bool'),F('Contact radius px','perception','perception.ros__parameters.drivable_contact_radius_px','int'),F('Contact vertical tolerance px','perception','perception.ros__parameters.drivable_contact_vertical_tolerance_px','int'),F('Contact min samples','perception','perception.ros__parameters.drivable_contact_min_samples','int'),F('Contact min fraction','perception','perception.ros__parameters.drivable_contact_min_fraction')],
    '4.2.3':[F('Track confirm hits','perception','perception.ros__parameters.track_confirm_hits','int'),F('Blocked confirm frames','perception','perception.ros__parameters.blocked_confirm_frames','int'),F('Clear confirm frames','perception','perception.ros__parameters.clear_confirm_frames','int')],
    '4.2.4':[F('Track max missed frames','perception','perception.ros__parameters.track_max_missed_frames','int'),F('Track match distance m','perception','perception.ros__parameters.track_match_distance_m'),F('Clearing obstacle margin m','perception','perception.ros__parameters.clearing_obstacle_margin_m')],
    '4.2.5':[F('Minimum obstacle confidence','perception','perception.ros__parameters.minimum_obstacle_confidence', 'float',true),F('Metric maximum forward m','perception','perception.ros__parameters.metric_maximum_forward_m','float',true)],
    '4.3.1':[F('Ground origin X px','perception','perception.ros__parameters.ground_origin_x_px'),F('Ground origin Y px','perception','perception.ros__parameters.ground_origin_y_px'),F('Meters/pixel X','perception','perception.ros__parameters.ground_meters_per_pixel_x'),F('Meters/pixel Y','perception','perception.ros__parameters.ground_meters_per_pixel_y')],
    '4.3.2':[F('Metric min forward m','perception','perception.ros__parameters.metric_minimum_forward_m'),F('Metric max forward m','perception','perception.ros__parameters.metric_maximum_forward_m'),F('Metric max abs lateral m','perception','perception.ros__parameters.metric_maximum_abs_left_m'),F('Calibration validated','perception','perception.ros__parameters.camera_metric_calibration_validated','bool',true)],
    '4.3.3':[F('Forward offset m','perception','perception.ros__parameters.metric_forward_offset_m'),F('Lateral offset m','perception','perception.ros__parameters.metric_lateral_offset_m')],
    '4.3.4':[F('Track EMA alpha','perception','perception.ros__parameters.track_ema_alpha'),F('Association distance m','bbox_calibration','runtime.association_distance_m'),F('Max track age frames','bbox_calibration','runtime.max_track_age_frames','int')],
    '4.3.5':[F('BBox estimator mode','bbox_calibration','runtime.mode','string'),F('Hybrid area weight','bbox_calibration','runtime.hybrid_area_weight'),F('BBox EMA alpha','bbox_calibration','runtime.ema_alpha')],
    '4.4.1':[F('Drivable sample rows','perception','perception.ros__parameters.drivable_space_sample_rows','int'),F('Min pixels per row','perception','perception.ros__parameters.drivable_space_min_pixels_per_row','int'),F('Pixel stride','perception','perception.ros__parameters.drivable_space_pixel_stride_px','int')],
    '4.4.2':[F('Drivable near m','perception','perception.ros__parameters.drivable_space_near_m'),F('Drivable far m','perception','perception.ros__parameters.drivable_space_far_m'),F('Drivable max abs lateral m','perception','perception.ros__parameters.drivable_space_max_abs_left_m')],
    '4.5.1':[F('Lane threshold','perception','perception.ros__parameters.lane_threshold')],
    '4.5.2':[F('Lane EMA alpha','perception','perception.ros__parameters.lane_ema_alpha')],
    '4.5.3':[F('Edge warning clearance m','perception','perception.ros__parameters.edge_warning_clearance_m'),F('Edge critical clearance m','perception','perception.ros__parameters.edge_critical_clearance_m'),F('Edge release clearance m','perception','perception.ros__parameters.edge_release_clearance_m'),F('State confirm frames','perception','perception.ros__parameters.state_confirm_frames','int'),F('Release confirm frames','perception','perception.ros__parameters.release_confirm_frames','int')],
    '4.5.4':[F('Center deadband m','perception','perception.ros__parameters.center_deadband_m'),F('Lane lookahead near m','perception','perception.ros__parameters.lane_lookahead_near_m'),F('Lane lookahead far m','perception','perception.ros__parameters.lane_lookahead_far_m'),F('Lane min valid rows','perception','perception.ros__parameters.lane_minimum_valid_rows','int')],
    '4.6.1':[F('Dark luma','perception','perception.ros__parameters.camera_health_dark_luma','int'),F('Bright luma','perception','perception.ros__parameters.camera_health_bright_luma','int'),F('Extreme fraction','perception','perception.ros__parameters.camera_health_extreme_fraction'),F('Min stddev','perception','perception.ros__parameters.camera_health_min_stddev'),F('Min gradient','perception','perception.ros__parameters.camera_health_min_gradient'),F('Bad confirm frames','perception','perception.ros__parameters.camera_health_bad_confirm_frames','int')],
    '4.6.2':[F('Near-field min confidence','perception','perception.ros__parameters.near_field_min_confidence'),F('Center corridor fraction','perception','perception.ros__parameters.near_field_center_corridor_fraction'),F('Min bbox height fraction','perception','perception.ros__parameters.near_field_min_bbox_height_fraction'),F('Bottom ROI fraction','perception','perception.ros__parameters.near_field_bottom_roi_fraction'),F('Confirm frames','perception','perception.ros__parameters.near_field_confirm_frames','int'),F('Release frames','perception','perception.ros__parameters.near_field_release_frames','int')],
    '4.7.1':[F('Trajectory lateral margin m','trajectory_safety','trajectory_safety_supervisor.ros__parameters.trajectory_lateral_margin_m'),F('Path horizon m','trajectory_safety','trajectory_safety_supervisor.ros__parameters.path_horizon_m')],
    '4.7.2':[F('Planning lateral margin m','trajectory_safety','trajectory_safety_supervisor.ros__parameters.planning_lateral_margin_m'),F('Planning max abs lateral m','trajectory_safety','trajectory_safety_supervisor.ros__parameters.planning_max_abs_lateral_m')],
    '4.7.3':[F('Slow path distance m','trajectory_safety','trajectory_safety_supervisor.ros__parameters.slow_path_distance_m'),F('Minimum slow speed scale','trajectory_safety','trajectory_safety_supervisor.ros__parameters.minimum_slow_speed_scale'),F('Warning lane speed m/s','trajectory_safety','trajectory_safety_supervisor.ros__parameters.warning_lane_speed_mps')],
    '4.7.4':[F('Hard stop path distance m','trajectory_safety','trajectory_safety_supervisor.ros__parameters.hard_stop_path_distance_m'),F('Immediate hard stop m','trajectory_safety','trajectory_safety_supervisor.ros__parameters.immediate_command_hard_stop_m'),F('Command collision horizon m','trajectory_safety','trajectory_safety_supervisor.ros__parameters.command_collision_horizon_m')],
    '4.7.5':[F('Avoidance speed m/s','trajectory_safety','trajectory_safety_supervisor.ros__parameters.avoidance_speed_mps'),F('Avoidance side margin m','trajectory_safety','trajectory_safety_supervisor.ros__parameters.avoidance_side_margin_m'),F('Critical lane speed m/s','trajectory_safety','trajectory_safety_supervisor.ros__parameters.critical_lane_speed_mps')],
    '4.8.1':[F('CPU inference FPS','perception','perception.ros__parameters.cpu_inference_fps'),F('CPU threads','perception','perception.ros__parameters.cpu_threads','int'),F('RViz publish max Hz','perception','perception.ros__parameters.rviz_max_publish_rate_hz'),F('Obstacle cloud max Hz','perception','perception.ros__parameters.obstacle_cloud_max_publish_rate_hz')],
    '4.9':[F('Metric calibration valid','perception','perception.ros__parameters.camera_metric_calibration_validated','bool',true),F('Lane safety enabled','perception','perception.ros__parameters.lane_safety_enabled','bool',true),F('Near-field enabled','perception','perception.ros__parameters.near_field_emergency_enabled','bool',true)],
    '4.10':[F('Confidence threshold','perception','perception.ros__parameters.confidence_threshold','float',true),F('Obstacle confidence','perception','perception.ros__parameters.minimum_obstacle_confidence','float',true),F('Lane threshold','perception','perception.ros__parameters.lane_threshold','float',true),F('Track EMA','perception','perception.ros__parameters.track_ema_alpha','float',true)],
    '4.11':[]
  },
  steering:{
    '4.1':[F('PWM frequency Hz','foc_thesis','foc_thesis.runtime.pwm_frequency_hz','int',true),F('Telemetry rate Hz','foc_thesis','foc_thesis.runtime.telemetry_rate_hz','int'),F('Command timeout ms','foc_thesis','foc_thesis.runtime.command_timeout_ms','int')],
    '4.2.1':[F('Calibration sample count','foc_thesis','foc_thesis.current_vbus_calibration.sample_count','int'),F('Ia offset ADC','foc_thesis','foc_thesis.current_vbus_calibration.ia_offset_adc'),F('Ib offset ADC','foc_thesis','foc_thesis.current_vbus_calibration.ib_offset_adc'),F('Current gain A/count','foc_thesis','foc_thesis.current_vbus_calibration.current_gain_a_per_count'),F('Vbus scale V/count','foc_thesis','foc_thesis.current_vbus_calibration.vbus_scale_v_per_count')],
    '4.2.2':[F('Encoder PPR','foc_thesis','foc_thesis.encoder_mechanical.ppr','int'),F('Encoder CPR','foc_thesis','foc_thesis.encoder_mechanical.cpr','int'),F('Direction','foc_thesis','foc_thesis.encoder_mechanical.direction','string'),F('Center count','foc_thesis','foc_thesis.encoder_mechanical.center_count','int'),F('Gear ratio','foc_thesis','foc_thesis.encoder_mechanical.gear_ratio'),F('Soft left limit deg','foc_thesis','foc_thesis.encoder_mechanical.soft_limit_left_deg'),F('Soft right limit deg','foc_thesis','foc_thesis.encoder_mechanical.soft_limit_right_deg')],
    '4.2.3':[F('Phase order','foc_thesis','foc_thesis.electrical_alignment.phase_order','string'),F('Pole pairs','foc_thesis','foc_thesis.electrical_alignment.pole_pairs','int'),F('Theta offset rad','foc_thesis','foc_thesis.electrical_alignment.theta_offset_rad'),F('Alignment Iq A','foc_thesis','foc_thesis.electrical_alignment.alignment_iq_a'),F('Sector count','foc_thesis','foc_thesis.electrical_alignment.sector_count','int')],
    '4.3':[F('Current Kp','foc_thesis','foc_thesis.current_loop.kp_i'),F('Current Ki','foc_thesis','foc_thesis.current_loop.ki_i'),F('Iq step A','foc_thesis','foc_thesis.current_loop.iq_step_a'),F('Iq limit A','foc_thesis','foc_thesis.current_loop.iq_limit_a'),F('Selected set','foc_thesis','foc_thesis.current_loop.selected_set','string')],
    '4.4':[F('Position Kp','foc_thesis','foc_thesis.position_loop.kp_pos'),F('Position Ki','foc_thesis','foc_thesis.position_loop.ki_pos'),F('Position Kd','foc_thesis','foc_thesis.position_loop.kd_pos'),F('Iq max A','foc_thesis','foc_thesis.position_loop.iq_max_a'),F('Iq slew A/s','foc_thesis','foc_thesis.position_loop.iq_slew_rate_a_per_s'),F('Tuning target deg','foc_thesis','foc_thesis.position_loop.tuning_target_deg')],
    '4.5':[F('Runs per direction','foc_thesis','foc_thesis.step_test.runs_per_direction','int'),F('Baseline hold s','foc_thesis','foc_thesis.step_test.baseline_hold_s'),F('Settling hold s','foc_thesis','foc_thesis.step_test.settling_hold_s'),F('Measured inner wheel deg','foc_thesis','foc_thesis.step_test.measured_inner_wheel_deg'),F('Measured outer wheel deg','foc_thesis','foc_thesis.step_test.measured_outer_wheel_deg')],
    '4.6.1':[F('Physical left limit deg','esc','esc_ackermann.ros__parameters.steering_physical_left_limit_deg','float',true),F('Physical right limit deg','esc','esc_ackermann.ros__parameters.steering_physical_right_limit_deg','float',true),F('Operational limit deg','esc','esc_ackermann.ros__parameters.steering_physical_operational_limit_deg','float',true)],
    '4.6.2':[F('Runs per direction','foc_thesis','foc_thesis.step_test.runs_per_direction','int'),F('Steering LUT deadband deg','esc','esc_ackermann.ros__parameters.steering_lut_direction_deadband_deg')],
    '4.6.3':[F('Wheelbase m','esc','esc_ackermann.ros__parameters.wheelbase_m'),F('Track width m','esc','esc_ackermann.ros__parameters.track_width_m'),F('Inner wheel measured deg','foc_thesis','foc_thesis.step_test.measured_inner_wheel_deg'),F('Outer wheel measured deg','foc_thesis','foc_thesis.step_test.measured_outer_wheel_deg')],
    '4.7':[F('Sinus amplitude deg','foc_thesis','foc_thesis.tracking_test.amplitude_deg'),F('Frequency 0','foc_thesis','foc_thesis.tracking_test.frequencies_hz.0'),F('Frequency 1','foc_thesis','foc_thesis.tracking_test.frequencies_hz.1'),F('Frequency 2','foc_thesis','foc_thesis.tracking_test.frequencies_hz.2')],
    '4.8':[F('Load target deg','foc_thesis','foc_thesis.load_test.target_deg'),F('Selected load','foc_thesis','foc_thesis.load_test.selected_level','string'),F('Iq max A','foc_thesis','foc_thesis.position_loop.iq_max_a','float',true)],
    '4.9':[F('Overcurrent A','foc_thesis','foc_thesis.safety_limits.overcurrent_a'),F('Undervoltage V','foc_thesis','foc_thesis.safety_limits.undervoltage_v'),F('Overvoltage V','foc_thesis','foc_thesis.safety_limits.overvoltage_v'),F('Overtemperature C','foc_thesis','foc_thesis.safety_limits.overtemperature_c'),F('Command rate Hz','esc','esc_ackermann.ros__parameters.command_rate_hz','float',true),F('Serial TX rate Hz','esc','esc_ackermann.ros__parameters.serial_tx_rate_hz','float',true)],
    '4.10':[F('Current selected set','foc_thesis','foc_thesis.current_loop.selected_set','string',true),F('Position selected set','foc_thesis','foc_thesis.position_loop.selected_set','string',true),F('Physical calibration enabled','esc','esc_ackermann.ros__parameters.steering_physical_calibration_enabled','bool',true)],
    '4.11':[]
  }
};
function experimentSortKey(id){const final=id.startsWith('F')?1:0;const nums=(id.match(/\d+/g)||[]).map(Number);return [final,...nums]}
function compareExperiment(a,b){const A=experimentSortKey(a.id),B=experimentSortKey(b.id);for(let i=0;i<Math.max(A.length,B.length);i++){const d=(A[i]??-1)-(B[i]??-1);if(d)return d}return a.id.localeCompare(b.id)}
function effectiveExperimentList(){return [...(experiments[currentExp]||[])].sort(compareExperiment)}
function tuningFieldsFor(x){const catalog=(x.parameterFields||[]).filter(p=>p.yamlFileKey||p.isGroundTruth);if(catalog.some(p=>p.yamlFileKey))return catalog;return WEB_TUNING[currentExp]?.[x.id]||[]}
function configValue(file,path){let n=configs[file]?.data;if(n==null)return undefined;for(const part of String(path||'').split('.').filter(Boolean)){if(Array.isArray(n)&&/^\d+$/.test(part))n=n[+part];else if(n&&typeof n==='object')n=n[part];else return undefined}return n}
function resolveMetricPath(path){if(!path)return undefined;if(path==='derived.cte_m')return derivedCte();if(path==='derived.endpoint_error_m')return derivedEndpoint();if(path==='derived.path_heading_error_rad')return derivedHeadingError();if(path==='derived.velocity_error_mps')return (+raw('esc_drive_actual')||0)-(+obj('cmd_final').linear_x||0);if(path==='derived.steering_error_rad')return (+raw('esc_steer_actual')||0)-(+raw('esc_steer_target')||0);if(Object.prototype.hasOwnProperty.call(state,path))return state[path];const parts=path.split('.');for(let n=parts.length-1;n>0;n--){const root=parts.slice(0,n).join('.');if(Object.prototype.hasOwnProperty.call(state,root)){let v=state[root];for(const p of parts.slice(n)){if(v==null)return undefined;v=v[p]}return v}}return undefined}
function currentPose(){const g=obj('ekf_global');if(Number.isFinite(+g.x))return g;const l=obj('ekf_local');return Number.isFinite(+l.x)?l:null}
function nearestPathInfo(){const pose=currentPose(),pts=obj('local_path').points||obj('nav_path').points||[];if(!pose||!pts.length)return null;let best=null;for(const p of pts){const d=Math.hypot((+p[0])-pose.x,(+p[1])-pose.y);if(!best||d<best.d)best={d,p}}return best}
function derivedCte(){return nearestPathInfo()?.d}
function derivedEndpoint(){const pose=currentPose(),goal=obj('goal_pose');if(!pose||!Number.isFinite(+goal.x))return undefined;return Math.hypot(pose.x-goal.x,pose.y-goal.y)}
function wrapPi(v){while(v>Math.PI)v-=2*Math.PI;while(v<-Math.PI)v+=2*Math.PI;return v}
function derivedHeadingError(){const pose=currentPose(),n=nearestPathInfo();if(!pose||!n||!Number.isFinite(+n.p[2]))return undefined;return wrapPi((pose.yaw||0)-(+n.p[2]))}
function captureLabTelemetry(){if(!selectedExperiment)return;const now=Date.now(),paths=new Set(Object.values(selectedExperiment.liveSeries||{}));['esc_drive_target','esc_drive_actual','esc_steer_target','esc_steer_actual','imu.gz','lidar.range_center_m','lidar.valid_ratio_pct','lidar.scan_rate_hz','perception_performance.fps','foc_telemetry.iq_a','foc_telemetry.id_a'].forEach(p=>paths.add(p));for(const path of paths){const v=resolveMetricPath(path);if(typeof v!=='number'||!Number.isFinite(v))continue;const a=metricHistory.get(path)||[];a.push({t:now,v});while(a.length>900)a.shift();metricHistory.set(path,a)}const g=selectedExperiment.graphs?.[selectedGraphIndex];if(g?.type==='scatter'){const xv=resolveMetricPath(g.xSeries),yv=resolveMetricPath(g.ySeries);if(Number.isFinite(+xv)&&Number.isFinite(+yv)){const key=`${currentExp}:${selectedExperiment.id}:${selectedGraphIndex}`,a=scatterHistory.get(key)||[];a.push({x:+xv,y:+yv});while(a.length>900)a.shift();scatterHistory.set(key,a)}}}
function visitedKey(){return `adv-visited-${currentExp}`}
function visitedSet(){try{return new Set(JSON.parse(localStorage.getItem(visitedKey())||'[]'))}catch(_){return new Set()}}
function markVisited(id){const s=visitedSet();s.add(id);localStorage.setItem(visitedKey(),JSON.stringify([...s]));renderChapterProgress()}
function renderChapterProgress(){const total=(experiments[currentExp]||[]).length,v=visitedSet().size,p=total?Math.min(100,Math.round(v/total*100)):0;setText('chapterProgressText',`${v} / ${total} dibuka`);setText('chapterProgressPct',p+'%');$('chapterProgressBar').style.width=p+'%'}
async function loadExperiments(){try{experiments=await (await fetch('/api/experiments',{cache:'no-store'})).json();setText('labLeafCount',Object.values(experiments).reduce((n,a)=>n+(a?.length||0),0));setText('navTestCount',(experiments.navigation||[]).length);setText('perTestCount',(experiments.perception||[]).length);setText('escTestCount',(experiments.steering||[]).length);renderExperimentList();const list=effectiveExperimentList();if(list.length)selectExperimentById(list[0].id)}catch(e){$('experimentList').innerHTML='<div class="empty-state">Catalog unavailable: '+escapeHtml(e.message)+'</div>'}}
function renderExperimentList(){const term=($('experimentSearch')?.value||'').trim().toLowerCase();const list=effectiveExperimentList().filter(x=>!term||`${x.id} ${x.section} ${x.groupTitle}`.toLowerCase().includes(term));const visited=visitedSet();let lastGroup='',html='';for(const x of list){const group=x.id.startsWith('F')?'FINAL THESIS DATASET':x.groupTitle||x.groupId||'BAB IV';if(group!==lastGroup){html+=`<div class="chapter-group"><span>${escapeHtml(group)}</span></div>`;lastGroup=group}html+=`<button class="experiment-item ${selectedExperiment?.id===x.id?'active':''}" data-id="${escapeHtml(x.id)}"><i>${visited.has(x.id)?'✓':'○'}</i><div><span>${escapeHtml(x.id)}</span><b>${escapeHtml(x.section||x.id)}</b><small>${(x.tableNames||[]).length} tabel • ${(x.graphCaptions||[]).length} grafik • ${tuningFieldsFor(x).filter(p=>p.yamlFileKey).length} parameter</small></div></button>`} $('experimentList').innerHTML=html||'<div class="empty-state">Tidak ada subbab yang cocok.</div>';qa('.experiment-item',$('experimentList')).forEach(e=>e.onclick=()=>selectExperimentById(e.dataset.id));setText('chapterDomainTitle',currentExp==='navigation'?'Navigasi':currentExp==='perception'?'Persepsi':'ESC / FOC');renderChapterProgress()}
function selectExperimentById(id){const x=(experiments[currentExp]||[]).find(v=>v.id===id);if(!x)return;selectedExperiment=x;selectedTableIndex=0;selectedGraphIndex=0;metricHistory.clear();scatterHistory.clear();markVisited(id);renderExperimentList();renderSelectedExperiment()}
function renderSelectedExperiment(){const x=selectedExperiment;if(!x)return;setText('experimentGroup',x.groupTitle||x.groupId||currentExp.toUpperCase());setText('experimentTitle',x.section||x.id);setText('experimentSubtitle',`${currentExp==='navigation'?'Navigasi':currentExp==='perception'?'Persepsi':'ESC / FOC'} • source catalog ${x.id} • data aktual ROS, tanpa dummy.`);setText('experimentTableBadge',`${(x.tableNames||[]).length} TABLE`);setText('experimentGraphBadge',`${(x.graphCaptions||[]).length} GRAPH`);setText('experimentRawMetadata',JSON.stringify(x,null,2));renderTuningFields();renderLabTabs();renderExperimentGraphs();renderExperimentTable();renderContextVisual();renderSourceAudit()}
function renderTuningFields(){const x=selectedExperiment,fields=tuningFieldsFor(x),readOnly=obj('server').read_only===true;setText('labYamlMode',readOnly?'LOCKED':'WRITE');if(!fields.length){$('tuningFields').innerHTML='<div class="empty-state">Subbab ini adalah validasi/ringkasan; tidak ada parameter yang boleh diubah pada tahap ini.</div>';return}let html='';fields.forEach((p,i)=>{const isYaml=!!p.yamlFileKey,ro=p.kind==='yaml_readonly'||p.locked||readOnly;const val=isYaml?configValue(p.yamlFileKey,p.yamlPath):(localRunValues[`${currentExp}:${x.id}:${p.key||p.label}`]??p.placeholder??'');const typ=p.kind==='bool'?'checkbox':p.kind==='int'||p.kind==='float'?'number':'text';const step=p.kind==='int'?'1':'any';const checked=typ==='checkbox'&&!!val;html+=`<div class="tuning-field ${ro?'readonly':''}"><div class="tuning-field-head"><label>${escapeHtml(p.label||p.key||'Parameter')}</label><span>${isYaml?escapeHtml(p.yamlFileKey):'RUN / GT'} ${ro?'• LOCKED':''}</span></div><div class="tuning-input-row">${typ==='checkbox'?`<label class="switch"><input id="tuneField-${i}" type="checkbox" ${checked?'checked':''} ${ro?'disabled':''}><i></i><b>${checked?'TRUE':'FALSE'}</b></label>`:`<input id="tuneField-${i}" type="${typ}" step="${step}" value="${escapeHtml(val??'')}" ${ro?'readonly':''}>`} ${ro?'':`<button class="param-save" data-field-index="${i}">${isYaml?'SAVE YAML':'SET'}</button>`}</div><code>${escapeHtml(p.yamlPath||p.key||'run identity')}</code>${p.help?`<small>${escapeHtml(p.help)}</small>`:''}</div>`});$('tuningFields').innerHTML=html;qa('.param-save',$('tuningFields')).forEach(b=>b.onclick=()=>saveTuningField(+b.dataset.fieldIndex));qa('.switch input',$('tuningFields')).forEach(e=>e.onchange=()=>{const b=q('b',e.parentElement);if(b)b.textContent=e.checked?'TRUE':'FALSE'})}
async function saveTuningField(i){const p=tuningFieldsFor(selectedExperiment)[i],el=$(`tuneField-${i}`);if(!p||!el)return;let value=p.kind==='bool'?el.checked:el.value;if(p.kind==='int')value=parseInt(value,10);if(p.kind==='float')value=parseFloat(value);if((p.kind==='int'||p.kind==='float')&&!Number.isFinite(value))return toast('Nilai numerik tidak valid',true);if(!p.yamlFileKey){localRunValues[`${currentExp}:${selectedExperiment.id}:${p.key||p.label}`]=value;toast('Nilai run/ground truth disimpan untuk sesi browser');return}confirmModal('Simpan parameter YAML',`${p.label}\n${p.yamlFileKey}:${p.yamlPath}\n→ ${String(value)}`,async()=>{try{const r=await fetch('/api/config/set',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({file_key:p.yamlFileKey,path:p.yamlPath,value})});const j=await r.json();toast(j.message||'YAML response',!r.ok);if(j.config?.files)configs=j.config.files;renderTuningFields();renderCalibration();renderTuning()}catch(e){toast('YAML save gagal: '+e.message,true)}})}
function renderLabTabs(){const x=selectedExperiment;$('tableTabs').innerHTML=(x.tableNames||[]).map((t,i)=>`<button class="${i===selectedTableIndex?'active':''}" data-table-index="${i}">${escapeHtml(t||`Tabel ${i+1}`)}</button>`).join('');qa('[data-table-index]',$('tableTabs')).forEach(b=>b.onclick=()=>{selectedTableIndex=+b.dataset.tableIndex;renderLabTabs();renderExperimentTable()});$('graphTabs').innerHTML=(x.graphCaptions||[]).map((g,i)=>`<button class="${i===selectedGraphIndex?'active':''}" data-graph-index="${i}">Grafik ${i+1}<span>${escapeHtml(g)}</span></button>`).join('');qa('[data-graph-index]',$('graphTabs')).forEach(b=>b.onclick=()=>{selectedGraphIndex=+b.dataset.graphIndex;renderLabTabs();renderExperimentGraphs()})}
function graphSeriesForCurrent(){const x=selectedExperiment,g=x?.graphs?.[selectedGraphIndex];if(g?.type==='scatter')return {scatter:g};const labels=g?.series?.length?g.series:Object.keys(x?.liveSeries||{});return {series:labels.map((label,i)=>({label,path:x.liveSeries?.[label]||label,color:LAB_COLORS[i%LAB_COLORS.length]}))}}
function renderExperimentGraphs(){const x=selectedExperiment;if(!x||!(x.graphCaptions||[]).length){$('experimentGraphs').innerHTML='<div class="empty-state">Subbab ini memang tidak memiliki grafik. Gunakan tabel/rekap sesuai metode pengujian.</div>';return}const caption=x.graphCaptions[selectedGraphIndex]||`Grafik ${selectedGraphIndex+1}`;$('experimentGraphs').innerHTML=`<div class="chart-card"><div class="chart-title"><b>${escapeHtml(caption)}</b><span id="chartDataStatus">WAITING DATA</span></div><canvas id="experimentChart" width="1400" height="420"></canvas><div id="chartLegend" class="chart-legend"></div></div>`;drawExperimentChart()}
function canvasFit(c,height=300){const r=c.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),w=Math.max(500,Math.round(r.width*dpr)),h=Math.round(height*dpr);if(c.width!==w||c.height!==h){c.width=w;c.height=h}return {ctx:c.getContext('2d'),w,h,dpr}}
function drawExperimentChart(){const c=$('experimentChart');if(!c||!selectedExperiment)return;const {ctx,w,h,dpr}=canvasFit(c,285),css=getComputedStyle(document.body);ctx.clearRect(0,0,w,h);ctx.fillStyle=css.getPropertyValue('--chart-bg')||'#071113';ctx.fillRect(0,0,w,h);const pad={l:55*dpr,r:18*dpr,t:22*dpr,b:35*dpr},spec=graphSeriesForCurrent();if(spec.scatter){const key=`${currentExp}:${selectedExperiment.id}:${selectedGraphIndex}`,pts=scatterHistory.get(key)||[];if(pts.length<2)return drawChartEmpty(ctx,w,h,'Menunggu pasangan data scatter '+spec.scatter.xSeries+' / '+spec.scatter.ySeries);let xs=pts.map(p=>p.x),ys=pts.map(p=>p.y),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys);if(xmin===xmax){xmin-=1;xmax+=1}if(ymin===ymax){ymin-=1;ymax+=1}drawGrid(ctx,w,h,pad,dpr,xmin,xmax,ymin,ymax);ctx.fillStyle=LAB_COLORS[0];for(const p of pts){const x=pad.l+(p.x-xmin)/(xmax-xmin)*(w-pad.l-pad.r),y=h-pad.b-(p.y-ymin)/(ymax-ymin)*(h-pad.t-pad.b);ctx.beginPath();ctx.arc(x,y,2.2*dpr,0,Math.PI*2);ctx.fill()}setText('chartLegend',`${spec.scatter.xSeries} ↔ ${spec.scatter.ySeries}`);setText('chartDataStatus',`${pts.length} POINTS`);return}const series=spec.series.map(s=>({...s,data:metricHistory.get(s.path)||[]})).filter(s=>s.data.length);if(!series.length)return drawChartEmpty(ctx,w,h,'Belum ada telemetry untuk grafik ini');const vals=series.flatMap(s=>s.data.map(p=>p.v)),times=series.flatMap(s=>s.data.map(p=>p.t)),tmin=Math.min(...times),tmax=Math.max(...times),vmin=Math.min(...vals),vmax=Math.max(...vals);const span=Math.max(.0001,vmax-vmin),lo=vmin-span*.12,hi=vmax+span*.12;drawGrid(ctx,w,h,pad,dpr,(tmin-tmax)/1000,0,lo,hi);for(const s of series){ctx.strokeStyle=s.color;ctx.lineWidth=2*dpr;ctx.beginPath();s.data.forEach((p,i)=>{const x=pad.l+(p.t-tmin)/Math.max(1,tmax-tmin)*(w-pad.l-pad.r),y=h-pad.b-(p.v-lo)/(hi-lo)*(h-pad.t-pad.b);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}$('chartLegend').innerHTML=series.map(s=>`<span><i style="background:${s.color}"></i>${escapeHtml(s.label)} <b>${fmt(s.data.at(-1)?.v,3)}</b></span>`).join('');setText('chartDataStatus',`${series.reduce((n,s)=>n+s.data.length,0)} SAMPLES`)}
function drawGrid(ctx,w,h,pad,dpr,xmin,xmax,ymin,ymax){ctx.strokeStyle='rgba(120,150,155,.16)';ctx.fillStyle='rgba(160,180,185,.7)';ctx.font=`${9*dpr}px ui-monospace`;for(let i=0;i<=4;i++){const y=pad.t+i/4*(h-pad.t-pad.b),v=ymax-i/4*(ymax-ymin);ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();ctx.fillText(Number.isFinite(v)?v.toFixed(3):'--',4*dpr,y+3*dpr)}for(let i=0;i<=5;i++){const x=pad.l+i/5*(w-pad.l-pad.r),v=xmin+i/5*(xmax-xmin);ctx.beginPath();ctx.moveTo(x,pad.t);ctx.lineTo(x,h-pad.b);ctx.stroke();ctx.fillText(Number.isFinite(v)?v.toFixed(1):'--',x-10*dpr,h-10*dpr)}}
function drawChartEmpty(ctx,w,h,msg){ctx.fillStyle='rgba(140,165,170,.7)';ctx.font=`13px ui-monospace`;ctx.textAlign='center';ctx.fillText(msg,w/2,h/2);ctx.textAlign='left';setText('chartDataStatus','WAITING DATA');setText('chartLegend','Source akan aktif otomatis ketika ROS publish.')}
function metricStats(path){const a=metricHistory.get(path)||[];if(!a.length)return null;const v=a.map(p=>p.v),mean=v.reduce((x,y)=>x+y,0)/v.length,rmse=Math.sqrt(v.reduce((x,y)=>x+y*y,0)/v.length);return {last:v.at(-1),mean,rmse,min:Math.min(...v),max:Math.max(...v),std:Math.sqrt(v.reduce((x,y)=>x+(y-mean)**2,0)/v.length),count:v.length}}
function primaryMetricPath(){return Object.values(selectedExperiment?.liveSeries||{})[0]}
function inferColumnValue(col){const k=String(col).toLowerCase(),variation=$('runVariation').value,condition=$('runCondition').value;if(k.includes('variasi')||k==='set'||k.includes('parameter')||k.includes('threshold')||k.includes('frequency')||k.includes('alpha')||k.includes('radius')||k.includes('penalty')||k.includes('weight'))return variation;if(k.includes('kondisi')||k.includes('skenario'))return condition;if(k.includes('satel'))return fmt(resolveMetricPath('lidar.valid_samples'),0);if(k.includes('dop'))return fmt(resolveMetricPath('lidar.dropout_pct'),2);if(k.includes('hacc'))return fmt(resolveMetricPath('lidar.range_center_m'),2);if(k.includes('rpm feedback')||k.includes('drive actual'))return fmt(raw('esc_drive_actual'),3);if(k.includes('rpm perintah')||k.includes('drive target'))return fmt(raw('esc_drive_target'),3);if(k.includes('steering perintah'))return fmt(deg(raw('esc_steer_target')),2);if(k==='feedback'||k.includes('steering actual'))return fmt(deg(raw('esc_steer_actual')),2);if(k.includes('endpoint')||k.includes('error akhir')||k.includes('stop error'))return fmt(derivedEndpoint(),3);if(k.includes('cte'))return fmt(derivedCte(),3);if(k.includes('heading'))return fmt(deg(derivedHeadingError()),2);if(k.includes('fps'))return fmt(resolveMetricPath('perception_performance.fps'),2);if(k.includes('confidence'))return fmt(resolveMetricPath('raw_detections.mean_confidence'),3);if(k.includes('status')||k.includes('keputusan'))return 'LIVE';if(k.includes('rmse')){const st=metricStats(primaryMetricPath());return st?fmt(st.rmse,4):'--'}if(k.includes('std')){const st=metricStats(primaryMetricPath());return st?fmt(st.std,4):'--'}return '--'}
function renderExperimentTable(){const x=selectedExperiment,cols=x?.tableColumns?.[selectedTableIndex]||[];const table=$('experimentTable');if(!cols.length){table.querySelector('thead').innerHTML='';table.querySelector('tbody').innerHTML='<tr><td>Subbab ini tidak mendefinisikan tabel.</td></tr>';return}table.querySelector('thead').innerHTML='<tr>'+cols.map(c=>`<th>${escapeHtml(c)}</th>`).join('')+'</tr>';table.querySelector('tbody').innerHTML='<tr class="live-preview-row">'+cols.map(c=>`<td>${escapeHtml(inferColumnValue(c))}</td>`).join('')+'</tr>';setText('tableLiveHint',`Tabel ${selectedTableIndex+1}/${x.tableColumns.length} • preview live; CSV raw/summary tersimpan saat Stop`)}
function renderContextVisual(){if(!selectedExperiment)return;const map=$('contextMap'),cam=$('contextCamera'),esc=$('contextEsc');map.style.display=currentExp==='navigation'?'block':'none';cam.style.display=currentExp==='perception'?'block':'none';esc.style.display=currentExp==='steering'?'block':'none';setText('contextTitle',currentExp==='navigation'?'Map • Path • Robot':currentExp==='perception'?'Camera • YOLOPv2':'FOC • Steering • Drive');if(currentExp==='navigation')drawExperimentMap();else if(currentExp==='perception')updateLabCamera();else drawExperimentEsc();renderContextMetrics()}
function drawExperimentMap(){const c=$('expMapCanvas'),m=obj('map_meta');if(!c||!mapImage||!m.width){if($('expMapEmpty'))$('expMapEmpty').style.display='grid';return}const {ctx,w,h,dpr}=canvasFit(c,310),scale=Math.min(w/mapImage.width,h/mapImage.height),dw=mapImage.width*scale,dh=mapImage.height*scale,ox=(w-dw)/2,oy=(h-dh)/2;ctx.clearRect(0,0,w,h);ctx.fillStyle='#050b0d';ctx.fillRect(0,0,w,h);ctx.drawImage(mapImage,ox,oy,dw,dh);const tr=(x,y)=>[ox+((x-m.origin_x)/m.resolution)*scale,oy+(m.height-(y-m.origin_y)/m.resolution)*scale];function path(key,color,width){const pts=obj(key).points||[];if(pts.length<2)return;ctx.strokeStyle=color;ctx.lineWidth=width*dpr;ctx.beginPath();pts.forEach((p,i)=>{const [x,y]=tr(p[0],p[1]);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}path('nav_path','#4aa8ff',2);path('local_path','#54d6e8',2);const pose=currentPose();if(pose){const [x,y]=tr(pose.x,pose.y);ctx.fillStyle='#48e0a4';ctx.beginPath();ctx.arc(x,y,7*dpr,0,Math.PI*2);ctx.fill()}const goal=obj('goal_pose');if(Number.isFinite(+goal.x)){const [x,y]=tr(goal.x,goal.y);ctx.strokeStyle='#ff7b8a';ctx.lineWidth=2*dpr;ctx.beginPath();ctx.arc(x,y,8*dpr,0,Math.PI*2);ctx.stroke()}$('expMapEmpty').style.display='none'}
function updateLabCamera(){if(currentExp!=='perception'||!$('expCameraImage'))return;if(!bool(raw('connected.camera'))){$('expCameraEmpty').style.display='grid';return}const im=new Image(),src='/api/camera.jpg?lab='+Date.now();im.onload=()=>{$('expCameraImage').src=src;$('expCameraImage').style.display='block';$('expCameraEmpty').style.display='none'};im.onerror=()=>{$('expCameraEmpty').style.display='grid'};im.src=src}
function drawExperimentEsc(){const c=$('expEscCanvas');if(!c)return;const {ctx,w,h,dpr}=canvasFit(c,310),cx=w/2;ctx.clearRect(0,0,w,h);ctx.fillStyle='#071113';ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(130,160,165,.25)';ctx.lineWidth=2*dpr;ctx.beginPath();ctx.moveTo(60*dpr,110*dpr);ctx.lineTo(w-60*dpr,110*dpr);ctx.stroke();const target=deg(raw('esc_steer_target'))||0,actual=deg(raw('esc_steer_actual'))||0,mapAngle=a=>cx+(Math.max(-45,Math.min(45,a))/45)*(w*.36);[['TARGET',target,'#ffc86b',85],['ACTUAL',actual,'#48e0a4',135]].forEach(([label,v,color,y])=>{ctx.fillStyle=color;ctx.fillRect(mapAngle(v)-3*dpr,y*dpr,6*dpr,48*dpr);ctx.font=`${11*dpr}px ui-monospace`;ctx.fillText(`${label} ${v.toFixed(2)}°`,18*dpr,(y+24)*dpr)});const foc=obj('foc_telemetry'),lines=[`Drive target ${fmt(raw('esc_drive_target'),3)} m/s`,`Drive actual ${fmt(raw('esc_drive_actual'),3)} m/s`,`Iq ${fmt(foc.iq_a??foc.iq,3)} A`,`Id ${fmt(foc.id_a??foc.id,3)} A`,`Vbus ${fmt(foc.vbus_v??foc.vbus,2)} V`];ctx.fillStyle='rgba(210,230,230,.82)';ctx.font=`${12*dpr}px ui-monospace`;lines.forEach((t,i)=>ctx.fillText(t,18*dpr,(210+i*22)*dpr))}
function renderContextMetrics(){let metrics=[];if(currentExp==='navigation')metrics=[['Pose X',fmt(currentPose()?.x,3)+' m'],['Pose Y',fmt(currentPose()?.y,3)+' m'],['CTE',fmt(derivedCte(),3)+' m'],['Endpoint',fmt(derivedEndpoint(),3)+' m'],['Path',fmt(obj('nav_path').length_m,2)+' m'],['Goal',obj('goal_state').state||'--']];else if(currentExp==='perception')metrics=[['Camera',bool(raw('connected.camera'))?'ONLINE':'OFF'],['Health',bool(raw('camera_healthy'))?'HEALTHY':'WAIT'],['FPS',fmt(resolveMetricPath('perception_performance.fps'),2)],['Objects',obj('object_points').count??'--'],['Lane',obj('lane_state').state||obj('lane_state').raw||'--'],['Near field',obj('near_field_state').state||obj('near_field_state').raw||'--']];else metrics=[['ESC',bool(raw('connected.esc_feedback'))?'ACK':'WAIT'],['Drive',fmt(raw('esc_drive_actual'),3)+' m/s'],['Steer',fmt(deg(raw('esc_steer_actual')),2)+'°'],['Error',fmt(deg(resolveMetricPath('derived.steering_error_rad')),2)+'°'],['Iq',fmt(resolveMetricPath('foc_telemetry.iq_a'),2)+' A'],['Mux',obj('esc_mux').raw||'--']];$('contextMetrics').innerHTML=metrics.map(([k,v])=>`<div><span>${escapeHtml(k)}</span><b>${escapeHtml(v)}</b></div>`).join('')}
function renderSourceAudit(){if(!selectedExperiment)return;const paths=[...new Set(Object.values(selectedExperiment.liveSeries||{}))],pills=paths.map(p=>{const v=resolveMetricPath(p),ok=v!==undefined&&v!==null;return `<span class="${ok?'ok':'wait'}"><i></i>${escapeHtml(p)}</span>`});$('sourceAvailability').innerHTML=pills.join('')||'<span class="wait"><i></i>No direct live-series binding; gunakan tabel/config evidence.</span>';const method=currentExp==='navigation'?'Nav2/localization telemetry + map/path + parameter YAML':currentExp==='perception'?'Camera/YOLOPv2 metrics + safety telemetry + parameter YAML':'ESC feedback + FOC telemetry + calibration/tuning YAML';setText('sourceMethod',method);setText('experimentSourceBadge',paths.some(p=>resolveMetricPath(p)!=null)?'LIVE SOURCE':'WAITING SOURCE')}
async function startWebRecording(){if(!selectedExperiment)return toast('Pilih subbab dulu',true);try{const r=await fetch('/api/experiment/record/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subsystem:currentExp,id:selectedExperiment.id,variation:$('runVariation').value,condition:$('runCondition').value,sample_rate_hz:+$('runSampleRate').value})});const j=await r.json();toast(j.message||'Recorder response',!r.ok);if(r.ok){recordStartedMs=Date.now();setRecordingUi(true,j.recording)}}catch(e){toast('Start CSV gagal: '+e.message,true)}}
async function stopWebRecording(){try{const r=await fetch('/api/experiment/record/stop',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const j=await r.json();toast(j.message||'Recorder response',!r.ok);setRecordingUi(false,j);if(r.ok){setText('recordPath','Raw: '+(j.raw_csv||'saved'));setText('recordMessage','Summary: '+(j.summary_csv||'')+' • Manifest: '+(j.manifest||''))}}catch(e){toast('Stop CSV gagal: '+e.message,true)}}
function setRecordingUi(active,info={}){$('startCsvBtn').disabled=active;$('stopCsvBtn').disabled=!active;setText('labRecorderState',active?'RECORDING':'IDLE');setText('recordChip',active?'RECORDING':'IDLE');$('recordChip').className='status-chip '+(active?'recording':'waiting');setText('labRecorderSamples',`${info.samples||0} samples`);if(!active){recordStartedMs=0;setText('recordElapsed','00:00.0')}}
async function pollRecorder(){try{const r=await fetch('/api/experiment/record/status',{cache:'no-store'}),j=await r.json();setRecordingUi(!!j.active,j);if(j.active&&!recordStartedMs&&j.started_at)recordStartedMs=Date.parse(j.started_at);if(j.active&&recordStartedMs){const sec=(Date.now()-recordStartedMs)/1000,min=Math.floor(sec/60);setText('recordElapsed',`${String(min).padStart(2,'0')}:${(sec-min*60).toFixed(1).padStart(4,'0')}`)}}catch(_){}}
$('startCsvBtn').onclick=startWebRecording;$('stopCsvBtn').onclick=stopWebRecording;$('refreshExperimentConfig').onclick=async()=>{await loadConfig();renderTuningFields();toast('YAML dimuat ulang')};$('experimentSearch').oninput=renderExperimentList;$('graphClearBtn').onclick=()=>{metricHistory.clear();scatterHistory.clear();renderExperimentGraphs()};
qa('.domain-tab').forEach(b=>b.onclick=()=>{qa('.domain-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentExp=b.dataset.exp;selectedExperiment=null;metricHistory.clear();scatterHistory.clear();renderExperimentList();const list=effectiveExperimentList();if(list.length)selectExperimentById(list[0].id)});
function renderLabWorkbench(){if(!selectedExperiment)return;captureLabTelemetry();if($('experimentChart'))drawExperimentChart();renderExperimentTable();renderContextVisual();renderSourceAudit()}
setInterval(renderLabWorkbench,350);setInterval(pollRecorder,1000);setInterval(updateLabCamera,900);

async function loadConfig(){try{const j=await (await fetch('/api/config',{cache:'no-store'})).json();configs=j.files||{};const keys=Object.keys(configs);$('configTabs').innerHTML=keys.map((k,i)=>`<button data-conf="${escapeHtml(k)}" class="${i?'':'active'}">${escapeHtml(k)}</button>`).join('');qa('[data-conf]',$('configTabs')).forEach(b=>b.onclick=()=>{qa('[data-conf]',$('configTabs')).forEach(x=>x.classList.remove('active'));b.classList.add('active');showConfig(b.dataset.conf)});if(keys[0])showConfig(keys[0]);renderCalibration();renderTuning();}catch(e){setText('configView','Config API unavailable: '+e.message)}}
function showConfig(k){const c=configs[k]||{};setText('configView',`# ${c.path||k}\n\n${JSON.stringify(c.data??c,null,2)}`)}
$('exportStateBtn').onclick=()=>downloadBlob('adv_telemetry_'+stamp()+'.json','application/json',JSON.stringify({exported_at:new Date().toISOString(),state,updated},null,2));$('exportConfigBtn').onclick=()=>downloadBlob('adv_config_'+stamp()+'.json','application/json',JSON.stringify(configs,null,2));$('exportExperimentsBtn').onclick=()=>downloadBlob('adv_bab4_catalog_'+stamp()+'.json','application/json',JSON.stringify(experiments,null,2));$('exportCsvBtn').onclick=exportSummaryCsv;$('printReportBtn').onclick=()=>window.print();$('refreshConfigBtn').onclick=loadConfig;$('refreshStateBtn').onclick=fullState;
setInterval(()=>{renderTop();if(mapImage&&q('#page-navigation.active'))drawMap()},500);setInterval(updateCamera,700);setInterval(()=>{if(!mapImage||Date.now()-(obj('map_meta').at_ms||0)<3000)loadMapImage()},6000);
window.addEventListener('resize',()=>drawMap());connectSse();fullState();loadExperiments();loadConfig();loadMapImage();render();
