'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),https=require('https');
const root=process.env.AGV_ROOT||path.resolve(__dirname,'..');
const {chromium}=require(path.join(root,'.playwright/node_modules/playwright'));
const strict=process.env.STRICT_HARDWARE==='1', base=(process.env.ROS_WEB_BASE_URL||'http://127.0.0.1:5000').replace(/\/+$/,'');
const probe=url=>new Promise((resolve,reject)=>{const u=new URL(url),client=u.protocol==='https:'?https:http,req=client.get(u,res=>{res.resume();res.on('end',()=>res.statusCode>=200&&res.statusCode<400?resolve(res.statusCode):reject(new Error(`HTTP ${res.statusCode} ${url}`)))});req.setTimeout(3000,()=>req.destroy(new Error(`timeout ${url}`)));req.on('error',reject)});
const out=process.env.QA_SCREENSHOT_DIR||'/tmp/agv_ros_web_qa_20260910';fs.mkdirSync(out,{recursive:true});
const assert=(ok,msg)=>{if(!ok)throw new Error(msg)};
(async()=>{console.log(`ROS_WEB_BASE_URL=${base}`);try{await probe(base+'/api/health')}catch(e){throw new Error(`ROS Web tidak reachable di ${base}: ${e.message}`)}const browser=await chromium.launch({headless:true});const report={mode:strict?'strict-hardware':'layout-read-only',viewports:{},errors:[],badResponses:[],failedRequests:[],posts:[]};
for(const vp of [{name:'desktop-2560',width:2560,height:1440},{name:'desktop-1920',width:1920,height:1080},{name:'desktop-1600',width:1600,height:900},{name:'laptop-1366',width:1366,height:768},{name:'laptop-1280',width:1280,height:720},{name:'tablet-1024',width:1024,height:768},{name:'tablet-820',width:820,height:1180},{name:'tablet-768',width:768,height:1024},{name:'mobile-430',width:430,height:932},{name:'mobile-390',width:390,height:844},{name:'mobile-360',width:360,height:800}]){
 const page=await browser.newPage({viewport:{width:vp.width,height:vp.height}});const errors=[],bad=[],failed=[],posts=[];
 page.on('console',m=>{if(m.type()==='error'&&(strict||!m.text().includes('503 (Service Unavailable)')))errors.push(m.text())});page.on('pageerror',e=>errors.push(e.message));
 page.on('response',r=>{if(r.status()>=400&&!/\/api\/(camera\.jpg|map\.png|global_costmap\.png|local_costmap\.png)/.test(r.url()))bad.push(`${r.status()} ${r.url()}`)});
 page.on('requestfailed',r=>failed.push(`${r.url()} ${r.failure()?.errorText||''}`));page.on('request',r=>{if(r.method()==='POST')posts.push(r.url())});
 const response=await page.goto(base,{waitUntil:'domcontentloaded'});assert(response?.status()===200,`${vp.name}: index bukan 200`);await page.waitForTimeout(1200);
 const health=await page.evaluate(()=>fetch('/api/health').then(r=>r.json()));assert(health.ok&&health.ros&&health.read_only,`${vp.name}: backend bukan ROS read-only`);
 if(strict){const st=await page.evaluate(()=>fetch('/api/state').then(r=>r.json()));for(const k of ['connected.camera','connected.imu','connected.gnss','connected.neo3_mag','connected.esc_ready','connected.vesc_transport'])assert(st[k]===true,`${vp.name}: strict hardware ${k} false`)}
 for(const domain of ['overview','esc','navigation','perception']){await page.locator(`.top-domain[data-domain="${domain}"]`).click();await page.waitForTimeout(120);const tabs=page.locator('#workspaceTabs .workspace-tab');const n=await tabs.count();assert(n>0,`${vp.name}/${domain}: workspace kosong`);for(let i=0;i<n;i++){await tabs.nth(i).click();await page.waitForTimeout(80);const active=await page.locator('.page.active').count();assert(active===1,`${vp.name}/${domain}/tab${i}: active page ${active}`);const dims=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth}));assert(dims.scroll<=dims.client+2,`${vp.name}/${domain}/tab${i}: overflow ${dims.scroll}/${dims.client}`)}await page.screenshot({path:path.join(out,`${vp.name}-${domain}.png`),fullPage:true})}
 await page.locator('.top-domain[data-domain="navigation"]').click();const tune=page.locator('#workspaceTabs .workspace-tab',{hasText:'Tune'}).first();if(await tune.count()){await tune.click();await page.waitForTimeout(200);assert(await page.locator('#page-experiments').evaluate(e=>e.classList.contains('active')),`${vp.name}: tuning page tidak aktif`);for(const mode of ['task','tune','analyze']){await page.locator(`button[data-tuning-mode="${mode}"]`).click();assert(await page.locator('#page-experiments').getAttribute('data-tuning-mode')===mode,`${vp.name}: mode ${mode} gagal`)}for(const level of ['basic','advanced','expert']){await page.locator(`button[data-tuning-level="${level}"]`).click();assert(await page.locator('#page-experiments').getAttribute('data-tuning-level')===level,`${vp.name}: level ${level} gagal`)}const help=page.locator('[data-help-key]:visible').first();if(await help.count()){await help.click();assert(!(await page.locator('#helpDrawer').getAttribute('hidden')),`${vp.name}: help drawer tidak terbuka`);await page.locator('#helpCloseBtn').click()}}
 const a11y=await page.evaluate(()=>{const hidden=[...document.querySelectorAll('.workspace-pane[hidden]')];return hidden.flatMap(p=>[...p.querySelectorAll('a,button,input,select,textarea,[tabindex]')].filter(e=>!e.disabled&&e.tabIndex>=0).map(e=>e.id||e.outerHTML.slice(0,80)))});assert(a11y.length===0,`${vp.name}: focusable di hidden pane ${a11y.join(',')}`);
 const blockers=await page.evaluate(()=>[...document.querySelectorAll('body *')].filter(e=>{const c=getComputedStyle(e),r=e.getBoundingClientRect(),z=parseInt(c.zIndex||'0',10);return (c.position==='fixed'||c.position==='absolute')&&c.pointerEvents!=='none'&&z>0&&r.width>innerWidth*.7&&r.height>innerHeight*.7&&c.visibility!=='hidden'&&c.display!=='none'&&Number(c.opacity)===0}).map(e=>e.id||e.className));assert(blockers.length===0,`${vp.name}: invisible blocker ${blockers}`);
 const overlaps=await page.evaluate(()=>{const vis=[...document.querySelectorAll('button,input,select,textarea')].filter(e=>{if(e.closest('.sidebar-backdrop,.modal-backdrop,.help-backdrop,.toast-stack'))return false;const c=getComputedStyle(e),r=e.getBoundingClientRect();return c.display!=='none'&&c.visibility!=='hidden'&&r.width>4&&r.height>4});const bad=[];for(let i=0;i<vis.length;i++)for(let j=i+1;j<vis.length;j++){const a=vis[i],b=vis[j];if(a.contains(b)||b.contains(a))continue;const ra=a.getBoundingClientRect(),rb=b.getBoundingClientRect();const w=Math.min(ra.right,rb.right)-Math.max(ra.left,rb.left),h=Math.min(ra.bottom,rb.bottom)-Math.max(ra.top,rb.top);if(w>4&&h>4)bad.push(`${a.id||a.className}<->${b.id||b.className}`);if(bad.length>20)return bad}return bad});assert(overlaps.length===0,`${vp.name}: interactive overlap ${overlaps.join(' | ')}`);
 const sticky=await page.evaluate(()=>{const top=document.querySelector('.topbar')?.getBoundingClientRect(),tabs=document.querySelector('.workspace-tabs')?.getBoundingClientRect(),page=document.querySelector('.page.active');const first=page?[...page.children].find(e=>{const c=getComputedStyle(e),r=e.getBoundingClientRect();return c.display!=='none'&&c.visibility!=='hidden'&&r.height>0}):null,r=first?.getBoundingClientRect();return {barBottom:Math.max(top?.bottom||0,tabs?.bottom||0),firstTop:r?.top??9999}});assert(sticky.firstTop>=sticky.barBottom-2||sticky.firstTop<0,`${vp.name}: first content tertutup sticky ${JSON.stringify(sticky)}`);
 await page.screenshot({path:path.join(out,`${vp.name}.png`),fullPage:true});report.viewports[vp.name]={errors,bad,failed,posts};report.errors.push(...errors);report.badResponses.push(...bad);report.failedRequests.push(...failed);report.posts.push(...posts);await page.close()}
 assert(report.errors.length===0,`console/page errors: ${report.errors.join(' | ')}`);assert(report.badResponses.length===0,`HTTP >=400: ${report.badResponses.join(' | ')}`);assert(report.failedRequests.length===0,`request failed: ${report.failedRequests.join(' | ')}`);assert(report.posts.length===0,`read-only UI POST otomatis: ${report.posts.join(' | ')}`);
 console.log(JSON.stringify(report,null,2));await browser.close();console.log('PASS qa_ros_web_playwright');
})().catch(e=>{console.error('FAIL qa_ros_web_playwright:',e.stack||e);process.exit(1)});
