#include "esc/vesc_board.hpp"
#include <geometry_msgs/msg/twist.hpp>
#include <nav_msgs/msg/odometry.hpp>
#include <rclcpp/rclcpp.hpp>
#include <sensor_msgs/msg/battery_state.hpp>
#include <sensor_msgs/msg/joint_state.hpp>
#include <sensor_msgs/msg/temperature.hpp>
#include <std_msgs/msg/bool.hpp>
#include <std_msgs/msg/float64.hpp>
#include <std_msgs/msg/string.hpp>
#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <iomanip>
#include <memory>
#include <sstream>
#include <string>

using std::placeholders::_1;
namespace {
constexpr double kPi=3.14159265358979323846, kTwoPi=2.0*kPi;
rclcpp::QoS state_qos(){return rclcpp::QoS(rclcpp::KeepLast(1)).reliable().transient_local();}
}

class EscDriverNode final:public rclcpp::Node{
 public:
  EscDriverNode():Node("esc_driver"){
    vehicle_mode_=declare_parameter<std::string>("vehicle_mode","ackermann_dual_vesc");
    drive_port_=declare_parameter<std::string>("board0_port","/dev/vesc_drive");
    steer_port_=declare_parameter<std::string>("board1_port","/dev/vesc_steer");
    baud_=declare_parameter<int>("baud",921600);
    cmd_topic_=declare_parameter<std::string>("cmd_vel_topic","/cmd_vel/actuator");
    odom_topic_=declare_parameter<std::string>("odom_topic","/esc/odom");
    odom_frame_=declare_parameter<std::string>("odom_frame","odom"); base_frame_=declare_parameter<std::string>("base_frame","base_footprint");
    wheelbase_=declare_parameter<double>("wheelbase",0.70); track_width_=declare_parameter<double>("track_width",0.55); wheel_radius_=declare_parameter<double>("wheel_radius",0.145);
    drive_left_pole_pairs_=declare_parameter<double>("drive_left_pole_pairs",15.0); drive_right_pole_pairs_=declare_parameter<double>("drive_right_pole_pairs",15.0);
    drive_left_gear_=declare_parameter<double>("drive_left_gear_ratio",1.0); drive_right_gear_=declare_parameter<double>("drive_right_gear_ratio",1.0);
    drive_left_scale_=declare_parameter<double>("drive_left_scale",1.0); drive_right_scale_=declare_parameter<double>("drive_right_scale",1.0);
    max_drive_erpm_=declare_parameter<double>("max_drive_erpm",15000.0); max_steering_rad_=declare_parameter<double>("max_steering_rad",0.34);
    min_speed_for_steering_mps_=declare_parameter<double>("min_speed_for_steering_mps",0.08); cmd_timeout_s_=declare_parameter<double>("cmd_timeout_s",0.25);
    telemetry_timeout_s_=declare_parameter<double>("telemetry_timeout_s",0.30); steering_cal_timeout_s_=declare_parameter<double>("steering_cal_timeout_s",0.75);
    require_steering_calibration_=declare_parameter<bool>("require_steering_calibration_for_motion",true); offline_zero_output_=declare_parameter<bool>("offline_zero_output",true); publish_joint_states_=declare_parameter<bool>("publish_joint_states",true);
    if(wheelbase_<=0||wheel_radius_<=0||drive_left_pole_pairs_<=0||drive_right_pole_pairs_<=0)throw std::invalid_argument("invalid ESC geometry/pole-pair configuration");
    drive_=std::make_unique<esc::VescBoard>(drive_port_,baud_); steer_=std::make_unique<esc::VescBoard>(steer_port_,baud_);
    cmd_sub_=create_subscription<geometry_msgs::msg::Twist>(cmd_topic_,rclcpp::QoS(10).reliable(),std::bind(&EscDriverNode::on_cmd,this,_1));
    odom_pub_=create_publisher<nav_msgs::msg::Odometry>(odom_topic_,10); speed_pub_=create_publisher<std_msgs::msg::Float64>("/esc/speed",10);
    drive_target_pub_=fp("/esc/drive_target_mps"); drive_actual_pub_=fp("/esc/drive_actual_mps"); steer_target_pub_=fp("/esc/steering_target_rad"); steer_actual_pub_=fp("/esc/steering_actual_rad");
    steer_raw_pub_=fp("/esc/steering_raw_ticks"); steer_feedback_raw_pub_=fp("/esc/steering_feedback_raw_rad"); steer_protocol_pub_=fp("/esc/steering_protocol_command_rad"); steer_uncal_pub_=fp("/esc/steering_uncalibrated_rad"); yaw_pub_=fp("/esc/yaw_rate_actual_rps"); kin_yaw_pub_=fp("/esc/kinematic_yaw_rate_rps");
    left_erpm_pub_=fp("/esc/drive/left/erpm"); right_erpm_pub_=fp("/esc/drive/right/erpm"); left_rpm_pub_=fp("/esc/drive/left/mechanical_rpm"); right_rpm_pub_=fp("/esc/drive/right/mechanical_rpm"); left_vel_pub_=fp("/esc/drive/left/velocity_mps"); right_vel_pub_=fp("/esc/drive/right/velocity_mps"); slip_pub_=fp("/esc/drive/slip_ratio");
    drive_conn_pub_=bp("/esc/drive/connected"); steer_conn_pub_=bp("/esc/steer/connected"); feedback_pub_=bp("/esc/feedback_valid"); ready_pub_=bp("/esc/ready"); armed_pub_=bp("/esc/armed"); encoder_ready_pub_=bp("/esc/steer/encoder_ready"); cal_ready_pub_=bp("/esc/steering_calibration/controller_ready");
    status_pub_=create_publisher<std_msgs::msg::String>("/esc/status",state_qos()); foc_pub_=create_publisher<std_msgs::msg::String>("/esc/foc/telemetry",state_qos()); source_pub_=create_publisher<std_msgs::msg::String>("/esc/drive/source",state_qos());
    joint_pub_=create_publisher<sensor_msgs::msg::JointState>("joint_states",10); battery_pub_=create_publisher<sensor_msgs::msg::BatteryState>("/esc/battery",10); temp_pub_=create_publisher<sensor_msgs::msg::Temperature>("/esc/temperature",10);
    timer_=create_wall_timer(std::chrono::milliseconds(20),std::bind(&EscDriverNode::tick,this));
    RCLCPP_INFO(get_logger(),"Native VESC 6.00 ESC: drive=%s steer=%s baud=%d role-gated dual-Hall + left encoder",drive_port_.c_str(),steer_port_.c_str(),baud_);
  }
 private:
  using FPub=rclcpp::Publisher<std_msgs::msg::Float64>::SharedPtr; using BPub=rclcpp::Publisher<std_msgs::msg::Bool>::SharedPtr;
  FPub fp(const char*n){return create_publisher<std_msgs::msg::Float64>(n,rclcpp::QoS(5).best_effort());} BPub bp(const char*n){return create_publisher<std_msgs::msg::Bool>(n,state_qos());}
  static void pf(const FPub&p,double v){std_msgs::msg::Float64 m;m.data=v;p->publish(m);} static void pb(const BPub&p,bool v){std_msgs::msg::Bool m;m.data=v;p->publish(m);} static void ps(const rclcpp::Publisher<std_msgs::msg::String>::SharedPtr&p,const std::string&v){std_msgs::msg::String m;m.data=v;p->publish(m);}
  void on_cmd(const geometry_msgs::msg::Twist::SharedPtr m){if(!std::isfinite(m->linear.x)||!std::isfinite(m->angular.z))return;last_cmd_msg_=*m;last_cmd_=now();have_cmd_=true;}
  double steering_target()const{const double v=last_cmd_msg_.linear.x,w=last_cmd_msg_.angular.z;if(std::abs(v)<min_speed_for_steering_mps_){if(steer_->steering_cal().valid)return std::clamp(steer_->steering_cal().steering_deg*kPi/180.0,-max_steering_rad_,max_steering_rad_);return 0.0;}return std::clamp(std::atan(wheelbase_*w/v),-max_steering_rad_,max_steering_rad_);}
  double mps_to_erpm(double v,double pp,double gear,double scale)const{return std::clamp(v*60.0/(kTwoPi*wheel_radius_)*pp*gear*scale,-max_drive_erpm_,max_drive_erpm_);} double erpm_to_mps(double e,double pp,double gear,double scale)const{return (e/(pp*gear*scale))*kTwoPi/60.0*wheel_radius_;}
  bool drive_role_ok()const{return drive_->role()==esc::VescRole::DRIVE_DUAL_HALL;} bool steer_role_ok()const{return steer_->role()==esc::VescRole::STEER_LEFT_ENCODER;}
  bool drive_feedback_ok()const{return drive_->connected()&&drive_role_ok()&&drive_->values_fresh(false,telemetry_timeout_s_)&&drive_->values_fresh(true,telemetry_timeout_s_)&&drive_->values(false).fault==0&&drive_->values(true).fault==0;}
  bool encoder_ok()const{const auto&c=steer_->steering_cal();return steer_->connected()&&steer_role_ok()&&steer_->values_fresh(false,telemetry_timeout_s_)&&steer_->steering_cal_fresh(steering_cal_timeout_s_)&&c.encoder_configured&&c.fault==0&&(!require_steering_calibration_||(c.calibrated&&c.homed&&c.synced));}
  void poll_requests(){drive_->poll();steer_->poll();if(drive_->connected()){if(!drive_->role_known()||tick_count_%50==1)drive_->request_platform_info();drive_->request_values(false);drive_->request_values(true);}if(steer_->connected()){if(!steer_->role_known()||tick_count_%50==2)steer_->request_platform_info();steer_->request_values(false);if(tick_count_%10==0)steer_->request_steering_cal();}}
  void command_actuators(bool cmd_fresh,bool ready){if(!drive_->connected())return;if(!ready||!cmd_fresh){if(drive_role_ok()){drive_->set_rpm(0,false);drive_->set_rpm(0,true);}return;}const double v=last_cmd_msg_.linear.x;const auto l=static_cast<std::int32_t>(std::lround(mps_to_erpm(v,drive_left_pole_pairs_,drive_left_gear_,drive_left_scale_)));const auto r=static_cast<std::int32_t>(std::lround(mps_to_erpm(v,drive_right_pole_pairs_,drive_right_gear_,drive_right_scale_)));drive_->set_rpm(l,false);drive_->set_rpm(r,true);if(steer_role_ok())steer_->set_steering_deg(steering_target()*180.0/kPi);}
  void publish_feedback(bool hw_ready,bool cmd_fresh){double vl=0,vr=0,v=0,steer_rad=0,yaw=0,slip=0;if(drive_feedback_ok()){vl=erpm_to_mps(drive_->values(false).erpm,drive_left_pole_pairs_,drive_left_gear_,drive_left_scale_);vr=erpm_to_mps(drive_->values(true).erpm,drive_right_pole_pairs_,drive_right_gear_,drive_right_scale_);v=0.5*(vl+vr);}if(steer_->steering_cal().valid)steer_rad=std::clamp(steer_->steering_cal().steering_deg*kPi/180.0,-max_steering_rad_,max_steering_rad_);if(wheelbase_>0)yaw=v*std::tan(steer_rad)/wheelbase_;if(drive_feedback_ok()){const double k=track_width_*std::tan(steer_rad)/(2.0*wheelbase_);const double el=v*(1.0-k),er=v*(1.0+k);const double residual=0.5*(std::abs(vl-el)+std::abs(vr-er));slip=residual/std::max(0.05,std::abs(v));}
    pf(left_erpm_pub_,drive_feedback_ok()?drive_->values(false).erpm:0);pf(right_erpm_pub_,drive_feedback_ok()?drive_->values(true).erpm:0);pf(left_rpm_pub_,drive_feedback_ok()?drive_->values(false).erpm/drive_left_pole_pairs_:0);pf(right_rpm_pub_,drive_feedback_ok()?drive_->values(true).erpm/drive_right_pole_pairs_:0);pf(left_vel_pub_,vl);pf(right_vel_pub_,vr);pf(slip_pub_,slip);pf(drive_actual_pub_,v);pf(speed_pub_,v);pf(steer_actual_pub_,steer_rad);pf(steer_feedback_raw_pub_,steer_rad);pf(steer_uncal_pub_,steer_rad);pf(yaw_pub_,yaw);pf(kin_yaw_pub_,yaw);pf(steer_raw_pub_,static_cast<double>(steer_->steering_cal().position));
    const double target=cmd_fresh?last_cmd_msg_.linear.x:0.0,st=cmd_fresh?steering_target():steer_rad;pf(drive_target_pub_,target);pf(steer_target_pub_,st);pf(steer_protocol_pub_,st);
    const bool d=drive_feedback_ok(),e=encoder_ok();pb(drive_conn_pub_,d);pb(steer_conn_pub_,steer_->connected()&&steer_role_ok());pb(encoder_ready_pub_,e);pb(cal_ready_pub_,e);pb(feedback_pub_,d&&e);pb(ready_pub_,hw_ready);pb(armed_pub_,hw_ready&&cmd_fresh);ps(source_pub_,d?"DUAL_HALL":"OFFLINE_ZERO");
    if(!d&&offline_zero_output_)publish_odom(0,0,false);else if(d&&e)publish_odom(v,yaw,true); publish_diagnostics(hw_ready,cmd_fresh,vl,vr,v,steer_rad,slip);publish_aux(d,e,vl,vr,steer_rad);}
  void publish_odom(double v,double yaw_rate,bool valid){const auto stamp=now();if(valid){const std::uint64_t gen=drive_->values(false).generation+drive_->values(true).generation;if(gen==last_odom_generation_)return;last_odom_generation_=gen;double dt=odom_time_valid_?std::clamp((stamp-last_odom_stamp_).seconds(),0.0,0.10):0.0;last_odom_stamp_=stamp;odom_time_valid_=true;if(dt>0){double mid=odom_yaw_+0.5*yaw_rate*dt;odom_x_+=v*std::cos(mid)*dt;odom_y_+=v*std::sin(mid)*dt;odom_yaw_=std::remainder(odom_yaw_+yaw_rate*dt,kTwoPi);}}else odom_time_valid_=false;nav_msgs::msg::Odometry o;o.header.stamp=stamp;o.header.frame_id=odom_frame_;o.child_frame_id=base_frame_;o.pose.pose.position.x=odom_x_;o.pose.pose.position.y=odom_y_;o.pose.pose.orientation.z=std::sin(0.5*odom_yaw_);o.pose.pose.orientation.w=std::cos(0.5*odom_yaw_);o.twist.twist.linear.x=v;o.twist.twist.angular.z=yaw_rate;const double big=1e6;o.pose.covariance[0]=valid?0.10:big;o.pose.covariance[7]=valid?0.10:big;o.pose.covariance[35]=valid?0.20:big;o.twist.covariance[0]=valid?0.04:big;o.twist.covariance[7]=valid?0.02:big;o.twist.covariance[35]=valid?0.10:big;odom_pub_->publish(o);}
  void publish_diagnostics(bool ready,bool cmd_fresh,double vl,double vr,double v,double s,double slip){std::ostringstream q;q<<std::boolalpha<<"protocol=VESC6.00;mode="<<vehicle_mode_<<";baud="<<baud_<<";drive_port="<<drive_port_<<";steer_port="<<steer_port_<<";drive_role="<<esc::vesc_role_name(drive_->role())<<";steer_role="<<esc::vesc_role_name(steer_->role())<<";drive="<<(drive_feedback_ok()?"READY":"OFFLINE")<<";steer="<<(encoder_ok()?"READY":"WAIT")<<";encoder_ready="<<encoder_ok()<<";ready="<<ready<<";armed="<<(ready&&cmd_fresh)<<";cmd_fresh="<<cmd_fresh<<";source="<<(drive_feedback_ok()?"DUAL_HALL":"OFFLINE_ZERO")<<";left_erpm="<<drive_->values(false).erpm<<";right_erpm="<<drive_->values(true).erpm<<";left_mps="<<vl<<";right_mps="<<vr<<";v_actual="<<v<<";steer_actual="<<s<<";slip_ratio="<<slip<<";left_fault="<<int(drive_->values(false).fault)<<";right_fault="<<int(drive_->values(true).fault)<<";steer_fault="<<int(steer_->steering_cal().fault);ps(status_pub_,q.str());std::ostringstream f;f<<"source=VESC6;left_erpm="<<drive_->values(false).erpm<<";right_erpm="<<drive_->values(true).erpm<<";left_iq_a="<<drive_->values(false).iq_a<<";right_iq_a="<<drive_->values(true).iq_a<<";left_id_a="<<drive_->values(false).id_a<<";right_id_a="<<drive_->values(true).id_a<<";left_vd_v="<<drive_->values(false).vd_v<<";right_vd_v="<<drive_->values(true).vd_v<<";left_vq_v="<<drive_->values(false).vq_v<<";right_vq_v="<<drive_->values(true).vq_v<<";vbus_v="<<drive_->values(false).vin_v<<";steering_deg="<<steer_->steering_cal().steering_deg;ps(foc_pub_,f.str());}
  void publish_aux(bool d,bool e,double vl,double vr,double steer_rad){if(d){sensor_msgs::msg::BatteryState b;b.header.stamp=now();b.voltage=static_cast<float>(0.5*(drive_->values(false).vin_v+drive_->values(true).vin_v));b.current=static_cast<float>(drive_->values(false).current_in_a+drive_->values(true).current_in_a);b.present=true;battery_pub_->publish(b);sensor_msgs::msg::Temperature t;t.header.stamp=b.header.stamp;t.temperature=0.5*(drive_->values(false).temp_mos_c+drive_->values(true).temp_mos_c);temp_pub_->publish(t);}if(publish_joint_states_&&d){const auto stamp=now();double dt=joint_time_valid_?std::clamp((stamp-last_joint_stamp_).seconds(),0.0,0.10):0.0;last_joint_stamp_=stamp;joint_time_valid_=true;double wl=vl/wheel_radius_,wr=vr/wheel_radius_;wheel_angle_l_+=wl*dt;wheel_angle_r_+=wr*dt;sensor_msgs::msg::JointState j;j.header.stamp=stamp;j.name={"front_left_wheel_joint","rear_left_wheel_joint","front_right_wheel_joint","rear_right_wheel_joint","steering_joint"};j.position={wheel_angle_l_,wheel_angle_l_,wheel_angle_r_,wheel_angle_r_,e?steer_rad:0.0};j.velocity={wl,wl,wr,wr,0.0};joint_pub_->publish(j);}}
  void tick(){++tick_count_;poll_requests();const bool cmd_fresh=have_cmd_&&((now()-last_cmd_).seconds()<cmd_timeout_s_);const bool ready=drive_feedback_ok()&&encoder_ok();command_actuators(cmd_fresh,ready);publish_feedback(ready,cmd_fresh);if((drive_->connected()&&!drive_role_ok())||(steer_->connected()&&!steer_role_ok()))RCLCPP_ERROR_THROTTLE(get_logger(),*get_clock(),3000,"ESC role mismatch drive=%s steer=%s; motion blocked",esc::vesc_role_name(drive_->role()),esc::vesc_role_name(steer_->role()));}
  std::string vehicle_mode_,drive_port_,steer_port_,cmd_topic_,odom_topic_,odom_frame_,base_frame_;int baud_{921600};double wheelbase_{.70},track_width_{.55},wheel_radius_{.145},drive_left_pole_pairs_{15},drive_right_pole_pairs_{15},drive_left_gear_{1},drive_right_gear_{1},drive_left_scale_{1},drive_right_scale_{1},max_drive_erpm_{15000},max_steering_rad_{.34},min_speed_for_steering_mps_{.08},cmd_timeout_s_{.25},telemetry_timeout_s_{.30},steering_cal_timeout_s_{.75};bool require_steering_calibration_{true},offline_zero_output_{true},publish_joint_states_{true};
  std::unique_ptr<esc::VescBoard>drive_,steer_;geometry_msgs::msg::Twist last_cmd_msg_{};rclcpp::Time last_cmd_{};bool have_cmd_{false};std::uint64_t tick_count_{0},last_odom_generation_{0};double odom_x_{0},odom_y_{0},odom_yaw_{0},wheel_angle_l_{0},wheel_angle_r_{0};rclcpp::Time last_odom_stamp_{},last_joint_stamp_{};bool odom_time_valid_{false},joint_time_valid_{false};
  rclcpp::Subscription<geometry_msgs::msg::Twist>::SharedPtr cmd_sub_;rclcpp::Publisher<nav_msgs::msg::Odometry>::SharedPtr odom_pub_;FPub speed_pub_,drive_target_pub_,drive_actual_pub_,steer_target_pub_,steer_actual_pub_,steer_raw_pub_,steer_feedback_raw_pub_,steer_protocol_pub_,steer_uncal_pub_,yaw_pub_,kin_yaw_pub_,left_erpm_pub_,right_erpm_pub_,left_rpm_pub_,right_rpm_pub_,left_vel_pub_,right_vel_pub_,slip_pub_;BPub drive_conn_pub_,steer_conn_pub_,feedback_pub_,ready_pub_,armed_pub_,encoder_ready_pub_,cal_ready_pub_;rclcpp::Publisher<std_msgs::msg::String>::SharedPtr status_pub_,foc_pub_,source_pub_;rclcpp::Publisher<sensor_msgs::msg::JointState>::SharedPtr joint_pub_;rclcpp::Publisher<sensor_msgs::msg::BatteryState>::SharedPtr battery_pub_;rclcpp::Publisher<sensor_msgs::msg::Temperature>::SharedPtr temp_pub_;rclcpp::TimerBase::SharedPtr timer_;
};
int main(int argc,char**argv){rclcpp::init(argc,argv);rclcpp::spin(std::make_shared<EscDriverNode>());rclcpp::shutdown();return 0;}
